import type { MarkShape } from "./map/marks.ts";
import type { SceneryKind } from "./map/scenery.ts";
import type { RGB } from "./map/terrain.ts";
import type { WarpKind } from "./map/warp.ts";
import { geoEqualEarth, geoEquirectangular, geoNaturalEarth1, type GeoProjection } from "d3-geo";

export type ThemeId = "morning" | "cabinet" | "wire" | "ops" | "blueprint" | "pirate" | "space" | "candy" | "bit8" | "bit16" | "bit64" | "realize" | "newsroom" | "pond" | "honeycomb" | "arcana" | "arcadia" | "nightcap" | "campus" | "lasso" | "drive" | "stitch" | "glass" | "club" | "pool" | "snow" | "sheet" | "terminal" | "prep" | "rail" | "aquarium" | "lava" | "radar" | "noir" | "arcade" | "stadium" | "popup" | "trainset" | "chalk" | "sketch" | "rave" | "cube" | "dual" | "realm" | "tactical" | "reef" | "blocks" | "pindrop" | "deli" | "marquee" | "crunch" | "towers" | "core" | "fold" | "machine" | "render" | "flap" | "desktop" | "vinyl" | "paper" | "shortwave" | "postcard" | "zine" | "stijl" | "herbarium" | "woodblock" | "tiramisu";
export type ViewMode = "2d" | "3d";

/**
 * Everything the canvas needs to draw one look. UI chrome (fonts, panel colours)
 * lives in style.css under [data-theme=...]; keep the two in step.
 */
export interface Theme {
  id: ThemeId;
  label: string;
  /**
   * A design being tried out (decision 105): left out of the Design menu and opened only by a link with
   * `?theme=<id>`, so it can be seen on the live site before it is listed. Shown under Experiments while it is on.
   */
  experimental?: boolean;
  defaultView: ViewMode;
  projection2d: () => GeoProjection;
  ocean: string;
  land: string;
  /**
   * Land texture: halftone dots, a dot matrix, a checkerboard dither, diagonal hatching, bevelled blocks like a
   * tiled game stage, pixel grass, loose paint strokes, or plain fill. Blocks, grass and paint use `textureInk2`
   * as their second colour.
   */
  landTexture: "halftone" | "matrix" | "dither" | "hatch" | "blocks" | "grass" | "brush" | "mottle" | "honeycomb" | "lilypads" | "crunch" | "none";
  /**
   * Screen pixels per canvas pixel. 1 draws at full resolution; 3 draws a third as many pixels and scales them up
   * unsmoothed, so lines, coasts and dots come out as chunky pixels (Stage Select and Overworld).
   */
  pixel: number;
  /** With `pixel` above 1: enlarge the canvas smoothed, so it looks soft like an early 3D console's picture. */
  smooth?: boolean;
  /** Globe only: draw the sphere's outline as a polygon of this many sides, like a low-poly model. */
  polyGlobe?: number;
  /** Distance haze: toward the globe's rim, or toward the far edge of a tilted map. The colour of the horizon. */
  fog?: string;
  /** Place dots as circles, squares (the pixel designs), diamonds, bevelled discs or hexagons. */
  dotShape: MarkShape;
  textureInk: string;
  textureInk2?: string;
  coast: string;
  coastWidth: number;
  /** Concentric strokes around coasts, the old engraved-map trick. */
  waterlines: number;
  waterline: string;
  oceanHatch: string | null;
  /**
   * A pattern over the sea in canvas pixels: "tiles" is a faint square grid like a stage built from tiles,
   * "shimmer" is short broken highlights like light on water. Its ink is `waterline`.
   */
  oceanPattern?: "tiles" | "shimmer" | "brush" | "mottle";
  /** A wide band of lighter water along every coast, like the shallows on a game's world map. */
  shallows?: string;
  /**
   * Land built like early 3D game terrain (src/map/terrain.ts, decision 63): a grid of triangles with heights and
   * baked light, coloured grass, rock and snow, standing on cliff walls textured in `cliff` (base, light, dark),
   * with a band of `shallows` along the coast. Lakes and rivers are left out, since they no longer line up with
   * the grid.
   */
  lowPoly?: { grass: RGB; rock: RGB; snow: RGB; snowShade: RGB; cliff: [string, string, string]; shallows: string };
  /** Map view only: tilt the flat map back this many degrees, seen in perspective like the ground in a 3D game. */
  tilt?: number;
  /** A sky drawn behind the map: zenith, middle and horizon colours, with clouds that pan with the camera. */
  sky?: [string, string, string];
  /** With `tilt`: the eye's distance from the picture in frame heights (default 1). Smaller is stronger perspective. */
  tiltEye?: number;
  /** With `tilt`: the draw distance, as the smallest perspective scale drawn (default 0.5). */
  tiltFar?: number;
  /** With `tilt`: the furthest out Map view may zoom (default 1.8). */
  tiltMinZoom?: number;
  /** The globe's radius at the widest zoom, as a share of the frame's shorter side (default 0.46). */
  globeScale?: number;
  /**
   * Land and sea drawn a way of their own instead of the fills and textures above (decision 70): "neon" is Night
   * Drive's glowing wireframe over a ruled sea (src/map/neon.ts), "stitch" is Cross Stitch's X stitches on linen
   * (src/map/stitch.ts), "glass" is Rose Window's leaded glass (src/map/glass.ts). The colours above still set the
   * sea, land, coast, grid and markers.
   * Decision 74 adds "sheet" (Spreadsheet's filled cells, src/map/sheet.ts), "terminal" (Market Terminal's
   * dot-matrix plot, src/map/terminal.ts), "club" (Country Club's embroidery and desk globe, src/map/club.ts) and
   * "rail" (Sleeper Car's on-board route display, src/map/rail.ts).
   * "fold" is Folding Cube's world on a cube, laid flat as the cube's net in Map view (src/map/fold.ts): it sets its
   * own camera, so places are placed and tuned through it rather than through `proj`.
   */
  surface?: "neon" | "stitch" | "glass" | "sheet" | "terminal" | "club" | "rail" | "aquarium" | "lava" | "radar" | "noir" | "arcade" | "stadium" | "popup" | "trainset" | "chalk" | "sketch" | "gloss" | "blocks" | "towers" | "core" | "fold" | "machine" | "render" | "flap" | "desktop" | "vinyl" | "paper" | "postcard" | "zine" | "stijl" | "herbarium" | "woodblock" | "tiramisu";
  /**
   * Decision 75: a camera that bends the whole picture after it is projected (src/map/warp.ts): "barrel" is a picture
   * tube's curve (Map view only), "stadium" a big screen seen at an angle from the stands, "desk" a map lying on a
   * desk under a canted camera. Places go through it too, and tapping inverts it.
   */
  warp?: WarpKind;
  /** Decision 75: the picture moves on its own (a radar sweep, a crowd wave), redrawn at most 20 times a second. */
  motion?: boolean;
  /** Decision 75: a pinned place gets a ring instead of a square frame, so nothing reads as a target box. */
  pinRing?: boolean;
  /**
   * With `tilt`: [the tilt at the widest zoom, the zoom by which it has risen to `tilt`], so zooming out lays the
   * map flatter and zooming in stands it up (Pop-up Book, decision 76).
   */
  tiltOut?: [number, number];
  graticule: string;
  graticuleDash: number[];
  river: string;
  lake: string;
  ice: string;
  relief: string;
  dot: string;
  dotStroke: string;
  /** Colour for places with a report in the last hour. */
  fresh: string;
  tuned: string;
  arc: string;
  glow: boolean;
  /** Globe only: a soft halo around the sphere. */
  atmosphere: string | null;
  /** Globe only: darkening toward the limb, so the sphere reads as lit from the upper left. */
  shade: string | null;
  /** Map only: a double rule around the sheet, like a printed chart. */
  neatline: boolean;
  /**
   * Decoration drawn under the dots (src/map/decor.ts): "sea" puts a few large engraved sea monsters and ships in
   * the big oceans, with wave marks over open water,
   * "space" adds a thin bright rim to the globe and faint stars in the flat map's ocean, "candy" puts small
   * outlined sweets in open ocean. Never text, never on land, never near a
   * place.
   */
  decor: "sea" | "space" | "candy" | null;
  /**
   * Pictures that say what a design is (src/map/scenery.ts, decision 69): lily pads and frogs, a moon with a
   * sleeping bear, The Course of Empire's landmarks, trick-rope loops with a denim sea, or Tarot's wheel, sun and
   * moon round the globe. Open ocean or outside the map only, never text.
   */
  scenery?: SceneryKind;
  /**
   * A picture shown through the land and nowhere else (decision 95): the land is a window onto it, with the sea,
   * lakes, ice, rivers and coasts drawn over it as usual. Fixed to the screen in Map view and to the sphere's disc in
   * Globe view, so it stays sharp at every zoom. A path under public/, loaded once; until it loads the land is `land`.
   */
  landImage?: string;
  /**
   * A design with its own camera and moving light (decision 71, src/map/scenes.ts), drawn as a still picture kept
   * off screen plus a few animated extras:
   * "club" a mirror ball globe and a light-up dance floor under a tilted camera;
   * "pool" the map on a swimming pool's floor under rippling light, and the globe afloat at night;
   * "snow" the globe in a snow globe, and the map through curved glass that bulges at the centre;
   * "rave" the map on an LED wall between the lighting rig and the DJ booth, and the globe a round screen over the
   * stage, with lasers sweeping round them.
   */
  scene?: "club" | "pool" | "snow" | "rave";
  /**
   * Map view only: the world seen through a round window at the frame's centre, like a game's minimap (Old Realm).
   * Places outside it are neither drawn nor tuned; the page draws the ring around it (src/map/minimap.ts).
   */
  minimap?: boolean;
}

export const THEMES: Record<ThemeId, Theme> = {
  morning: {
    id: "morning",
    label: "Morning Edition",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#f3efe4",
    land: "#e6e0d0",
    landTexture: "halftone",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(21,21,21,0.55)",
    coast: "#151515",
    coastWidth: 0.9,
    waterlines: 4,
    waterline: "rgba(21,21,21,0.16)",
    oceanHatch: null,
    graticule: "rgba(21,21,21,0.18)",
    graticuleDash: [2, 3],
    river: "rgba(21,21,21,0.45)",
    lake: "#f3efe4",
    ice: "#f7f4ec",
    relief: "rgba(21,21,21,0.55)",
    dot: "#151515",
    dotStroke: "#f3efe4",
    fresh: "#151515",
    tuned: "#151515",
    arc: "rgba(21,21,21,0.7)",
    glow: false,
    atmosphere: null,
    shade: "rgba(21,21,21,0.22)",
    neatline: true,
    decor: null,
  },
  cabinet: {
    id: "cabinet",
    label: "Cabinet Map",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#e4d3ab",
    land: "#efe2c2",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(58,42,24,0.4)",
    coast: "#3a2a18",
    coastWidth: 1,
    waterlines: 5,
    waterline: "rgba(58,42,24,0.13)",
    oceanHatch: "rgba(58,42,24,0.07)",
    graticule: "rgba(58,42,24,0.28)",
    graticuleDash: [],
    river: "rgba(40,70,95,0.55)",
    lake: "#dccaa0",
    ice: "#f4ecd8",
    relief: "rgba(58,42,24,0.6)",
    dot: "#3a2a18",
    dotStroke: "#efe2c2",
    fresh: "#8e2a1c",
    tuned: "#8e2a1c",
    arc: "rgba(142,42,28,0.75)",
    glow: false,
    atmosphere: null,
    shade: "rgba(58,42,24,0.3)",
    neatline: true,
    decor: null,
  },
  wire: {
    id: "wire",
    label: "Wire Room",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#020503",
    land: "#04100a",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(76,255,140,0.34)",
    coast: "rgba(96,255,150,0.62)",
    coastWidth: 0.7,
    waterlines: 0,
    waterline: "rgba(96,255,150,0.06)",
    oceanHatch: null,
    graticule: "rgba(96,255,150,0.09)",
    graticuleDash: [],
    river: "rgba(96,255,150,0.18)",
    lake: "#020503",
    ice: "#07170e",
    relief: "rgba(96,255,150,0.22)",
    dot: "#6dff9e",
    dotStroke: "#020503",
    fresh: "#e6fff0",
    tuned: "#e6fff0",
    arc: "rgba(109,255,158,0.8)",
    glow: true,
    atmosphere: "rgba(76,255,140,0.16)",
    shade: "rgba(0,0,0,0.55)",
    neatline: false,
    decor: null,
  },
  ops: {
    id: "ops",
    label: "Ops Room",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#0e1217",
    land: "#1a2028",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(170,186,204,0.3)",
    coast: "rgba(170,186,204,0.55)",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(170,186,204,0.06)",
    oceanHatch: null,
    graticule: "rgba(170,186,204,0.12)",
    graticuleDash: [1, 3],
    river: "rgba(120,170,200,0.22)",
    lake: "#0e1217",
    ice: "#232b35",
    relief: "rgba(170,186,204,0.2)",
    dot: "#c8d2dd",
    dotStroke: "#0e1217",
    fresh: "#43c1d3",
    tuned: "#43c1d3",
    arc: "rgba(67,193,211,0.85)",
    glow: false,
    atmosphere: "rgba(67,193,211,0.10)",
    shade: "rgba(0,0,0,0.45)",
    neatline: true,
    decor: null,
  },
  blueprint: {
    id: "blueprint",
    label: "Blueprint",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#17397a",
    land: "#1d4590",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(238,243,251,0.3)",
    coast: "#eef3fb",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(238,243,251,0.22)",
    oceanHatch: null,
    graticule: "rgba(238,243,251,0.16)",
    graticuleDash: [],
    river: "rgba(238,243,251,0.35)",
    lake: "#17397a",
    ice: "#2451a0",
    relief: "rgba(238,243,251,0.45)",
    dot: "#eef3fb",
    dotStroke: "#17397a",
    fresh: "#ff8a52",
    tuned: "#ff8a52",
    arc: "rgba(255,138,82,0.9)",
    glow: false,
    atmosphere: "rgba(238,243,251,0.12)",
    shade: "rgba(8,20,48,0.5)",
    neatline: true,
    decor: null,
  },
  pirate: {
    id: "pirate",
    label: "Pirate",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#b3cbc0",
    land: "#eddab0",
    landTexture: "none",
    pixel: 1,
    dotShape: "x",
    textureInk: "rgba(59,38,20,0.4)",
    coast: "#3b2614",
    coastWidth: 1.1,
    waterlines: 3,
    waterline: "rgba(59,38,20,0.2)",
    oceanHatch: null,
    graticule: "rgba(59,38,20,0.3)",
    graticuleDash: [5, 4],
    river: "rgba(40,78,88,0.5)",
    lake: "#b3cbc0",
    ice: "#f4e9cf",
    relief: "rgba(59,38,20,0.6)",
    dot: "#3b2614",
    dotStroke: "#eddab0",
    fresh: "#b0271d",
    tuned: "#b0271d",
    arc: "rgba(176,39,29,0.8)",
    glow: false,
    atmosphere: null,
    shade: "rgba(59,38,20,0.32)",
    neatline: true,
    decor: "sea",
  },
  space: {
    id: "space",
    label: "Space",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#070b20",
    land: "#1a2552",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(255,212,150,0.34)",
    coast: "rgba(160,200,255,0.75)",
    coastWidth: 0.7,
    waterlines: 0,
    waterline: "rgba(150,192,255,0.06)",
    oceanHatch: null,
    graticule: "rgba(150,192,255,0.24)",
    graticuleDash: [2, 5],
    river: "rgba(150,192,255,0.16)",
    lake: "#070b20",
    ice: "#222c5e",
    relief: "rgba(150,192,255,0.2)",
    dot: "#eef3ff",
    dotStroke: "#070b20",
    fresh: "#ffb454",
    tuned: "#ffb454",
    arc: "rgba(255,180,84,0.85)",
    glow: true,
    atmosphere: "rgba(110,170,255,0.24)",
    shade: "rgba(0,0,10,0.6)",
    neatline: true,
    decor: "space",
  },
  candy: {
    id: "candy",
    label: "Candy Shop",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#cbe8ff",
    land: "#ffd8ec",
    landTexture: "none",
    pixel: 1,
    dotShape: "gumdrop",
    textureInk: "rgba(226,127,180,0.3)",
    coast: "#e27fb4",
    coastWidth: 1.2,
    waterlines: 2,
    waterline: "rgba(255,255,255,0.85)",
    oceanHatch: null,
    graticule: "rgba(255,255,255,0.75)",
    graticuleDash: [2, 5],
    river: "rgba(110,170,225,0.7)",
    lake: "#cbe8ff",
    ice: "#ffffff",
    relief: "rgba(226,127,180,0.55)",
    dot: "#5b3f8c",
    dotStroke: "#ffffff",
    fresh: "#d9307a",
    tuned: "#d9307a",
    arc: "rgba(217,48,122,0.85)",
    glow: false,
    atmosphere: "rgba(255,170,215,0.5)",
    shade: "rgba(110,80,160,0.2)",
    neatline: false,
    decor: "candy",
  },
  // Nods to three generations of home consoles, each after the sense of place of one game series of its era, never
  // its art, names, logos or characters. Stage Select after Mega Man: hard 8-bit pixels, a wall of bevelled metal
  // blocks, riveted stage-select frames. Overworld after Final Fantasy's world maps: finer pixels, grass, sandy
  // shores and shallows, blue windows. Polygon Kingdom after Super Mario 64 and Ocarina of Time: a tilted camera
  // over triangle terrain with baked light, orange cliffs, a pale sky and fog at the draw distance, a soft picture,
  // bevelled gold markers floating over their shadows, and a menu title in ice blue (decision 63).
  bit8: {
    id: "bit8",
    label: "Stage Select",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#0000a8",
    land: "#008888",
    landTexture: "blocks",
    pixel: 3,
    dotShape: "square",
    textureInk: "#003c48",
    textureInk2: "#40e0d0",
    coast: "#000000",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(0,88,248,0.45)",
    oceanHatch: null,
    oceanPattern: "tiles",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#3cbcfc",
    lake: "#0000a8",
    ice: "#fcfcfc",
    relief: "#003c48",
    dot: "#fcfcfc",
    dotStroke: "#000000",
    fresh: "#f83800",
    tuned: "#f8b800",
    arc: "#f8b800",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  bit16: {
    id: "bit16",
    label: "Overworld",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2048a8",
    land: "#58a830",
    landTexture: "grass",
    pixel: 2,
    dotShape: "circle",
    textureInk: "#2f6c1c",
    textureInk2: "#98d860",
    coast: "#f0e0a0",
    coastWidth: 1.6,
    waterlines: 0,
    waterline: "rgba(210,236,255,0.6)",
    oceanHatch: null,
    oceanPattern: "shimmer",
    shallows: "#3c78d8",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#78b8f8",
    lake: "#3c78d8",
    ice: "#f8f8f8",
    relief: "#7a4a1c",
    dot: "#f8f8f8",
    dotStroke: "#101830",
    fresh: "#f8d030",
    tuned: "#f8d030",
    arc: "#f8d030",
    glow: false,
    atmosphere: "rgba(150,200,255,0.45)",
    shade: "rgba(0,0,40,0.45)",
    neatline: false,
    decor: null,
  },
  bit64: {
    id: "bit64",
    label: "Polygon Kingdom",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#3d8fdc",
    land: "#5cc83a",
    landTexture: "none",
    lowPoly: {
      grass: [92, 200, 58],
      rock: [165, 138, 106],
      snow: [244, 246, 255],
      snowShade: [185, 196, 224],
      cliff: ["#c0621e", "#e08a3a", "#8a3a0c"],
      shallows: "#62c6e6",
    },
    tilt: 58,
    sky: ["#6fb4f0", "#a9d6f7", "#e6f5fb"],
    fog: "#e6f5fb",
    pixel: 1.5,
    smooth: true,
    polyGlobe: 22,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0)",
    coast: "rgba(0,0,0,0)",
    coastWidth: 0,
    waterlines: 0,
    waterline: "rgba(159,216,248,0.4)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#3d8fdc",
    ice: "#f4f6ff",
    relief: "#6e4418",
    dot: "#ffd23a",
    dotStroke: "#8a5600",
    fresh: "#ff4a3d",
    tuned: "#ffffff",
    arc: "#ffffff",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },




  // Direct nods to the Mezmerize and Hypnotize covers (2005): black ground, dark red smeared paint, bone white, the
  // striped arcs, the blue face for fresh reports, a white stamped poster face over red marker lettering. No band
  // name or artwork is copied.
  realize: {
    id: "realize",
    label: "Realize",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#0b090a",
    land: "#4a1512",
    landTexture: "brush",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(150,32,28,0.5)",
    textureInk2: "rgba(0,0,0,0.5)",
    coast: "#d8ccb2",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "rgba(120,18,24,0.13)",
    oceanHatch: null,
    oceanPattern: "brush",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(216,204,178,0.22)",
    lake: "#0b090a",
    ice: "#6e645a",
    relief: "rgba(0,0,0,0.6)",
    dot: "#ece3d0",
    dotStroke: "#0b090a",
    fresh: "#7d9be0",
    tuned: "#d2263b",
    arc: "#d2263b",
    glow: false,
    atmosphere: "rgba(150,20,30,0.35)",
    shade: "rgba(0,0,0,0.7)",
    neatline: false,
    decor: null,
  },

  // A modern television news studio: the world on a glowing LED wall, glossy navy glass, white and red captions
  // along the bottom of the screen, and a crawl of headlines.
  newsroom: {
    id: "newsroom",
    label: "Newsroom",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#07163a",
    land: "#12357a",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(140,200,255,0.55)",
    coast: "#6cc4ff",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(108,196,255,0.2)",
    oceanHatch: null,
    graticule: "rgba(108,196,255,0.14)",
    graticuleDash: [],
    river: "rgba(108,196,255,0.3)",
    lake: "#07163a",
    ice: "#2a4f94",
    relief: "rgba(140,200,255,0.3)",
    dot: "#ffffff",
    dotStroke: "#051030",
    fresh: "#ff3b4e",
    tuned: "#ffffff",
    arc: "#ff3b4e",
    glow: true,
    atmosphere: "rgba(80,170,255,0.45)",
    shade: "rgba(0,4,20,0.6)",
    neatline: false,
    decor: null,
  },
  // A frog pond seen from above: murky green water, land as a mat of lily pads, pads with lotus flowers, frogs and
  // dragonflies in open water, lotus pink for fresh reports (decision 69).
  pond: {
    id: "pond",
    label: "Frog Pond",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2f6b5f",
    land: "#76b347",
    landTexture: "lilypads",
    pixel: 1,
    dotShape: "pad",
    textureInk: "rgba(190,232,130,0.6)",
    textureInk2: "rgba(40,110,40,0.4)",
    coast: "#24501d",
    coastWidth: 1.4,
    waterlines: 3,
    waterline: "rgba(190,235,215,0.35)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(190,235,215,0.5)",
    lake: "#2f6b5f",
    ice: "#e8f2e4",
    relief: "rgba(30,80,30,0.5)",
    dot: "#fff6d8",
    dotStroke: "#1e3b17",
    fresh: "#ff7eb6",
    tuned: "#ff7eb6",
    arc: "#ff7eb6",
    glow: false,
    atmosphere: "rgba(120,200,160,0.35)",
    shade: "rgba(0,30,20,0.45)",
    neatline: false,
    decor: null,
    scenery: "pond",
  },
  // Inside a hive, after the feel of Bee Movie: honey land built from hexagon cells over a dark hive, black and
  // yellow stripes in the chrome, hexagon markers.
  honeycomb: {
    id: "honeycomb",
    label: "Honeycomb",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2e1c07",
    land: "#f2b632",
    landTexture: "honeycomb",
    pixel: 1,
    dotShape: "hex",
    textureInk: "rgba(160,95,10,0.75)",
    textureInk2: "rgba(255,225,140,0.6)",
    coast: "#1a1004",
    coastWidth: 1.6,
    waterlines: 2,
    waterline: "rgba(242,182,50,0.18)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(160,95,10,0.6)",
    lake: "#2e1c07",
    ice: "#fbe7a8",
    relief: "rgba(120,70,5,0.6)",
    dot: "#1a1004",
    dotStroke: "#ffd84a",
    fresh: "#ffffff",
    tuned: "#ffffff",
    arc: "#ffffff",
    glow: false,
    atmosphere: "rgba(242,182,50,0.35)",
    shade: "rgba(0,0,0,0.55)",
    neatline: false,
    decor: null,
  },
  // A tarot card: deep violet, gold linework and stars, the sheet framed like a card, and on the globe a gold wheel
  // with a sun and a crescent moon beside it (src/map/scenery.ts).
  arcana: {
    id: "arcana",
    label: "Tarot",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    scenery: "arcana",
    globeScale: 0.4,
    ocean: "#1a1142",
    land: "#33235f",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "star5",
    textureInk: "rgba(232,196,110,0.4)",
    coast: "#e3bd62",
    coastWidth: 1.2,
    waterlines: 1,
    waterline: "rgba(227,189,98,0.25)",
    oceanHatch: null,
    graticule: "rgba(227,189,98,0.12)",
    graticuleDash: [1, 4],
    river: "rgba(227,189,98,0.3)",
    lake: "#1a1142",
    ice: "#46327a",
    relief: "rgba(227,189,98,0.45)",
    dot: "#f5e6c0",
    dotStroke: "#1a1142",
    fresh: "#ff9d5c",
    tuned: "#f5e6c0",
    arc: "#e3bd62",
    glow: false,
    atmosphere: "rgba(227,189,98,0.28)",
    shade: "rgba(5,0,20,0.6)",
    neatline: true,
    decor: null,
  },
  // Thomas Cole's The Course of Empire: Destruction (1836, public domain) in black and white, seen through the land
  // (decision 95): the continents are windows onto the painting, on a pale sea ruled in fine engraved lines with
  // engraved ripples along the coasts. Greys only, so fresh reports get the dotted ring.
  arcadia: {
    id: "arcadia",
    label: "Course of Empire",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    globeScale: 0.4,
    ocean: "#ececec",
    land: "#7a7a7a",
    landTexture: "none",
    landImage: "art/course-of-empire.jpg",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(17,17,17,0.5)",
    coast: "#111111",
    coastWidth: 1.4,
    waterlines: 3,
    waterline: "rgba(17,17,17,0.4)",
    oceanHatch: "rgba(17,17,17,0.24)",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(236,236,236,0.45)",
    lake: "#ececec",
    ice: "#f4f4f4",
    relief: "rgba(17,17,17,0.5)",
    dot: "#ffffff",
    dotStroke: "#111111",
    fresh: "#111111",
    tuned: "#111111",
    arc: "#111111",
    glow: false,
    atmosphere: "rgba(40,40,40,0.25)",
    shade: "rgba(0,0,0,0.45)",
    neatline: true,
    decor: null,
    scenery: "empire",
  },
  // A bedtime tea box: a watercolour night in periwinkle and sage, stars over the sea, and a bear in a red nightcap
  // asleep in the moon beside the globe (decision 69). The tea is in it too: the globe is the tea in a big cup on a
  // saucer, steam rising, amber where the tea meets the cup; teacups and steeping tea bags on the map's open sea;
  // teacup markers. Fresh reports take the cap's red.
  nightcap: {
    id: "nightcap",
    label: "Bedtime Tea",
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    // Small enough that the cup's rim, the saucer and the steam fit round the globe.
    globeScale: 0.28,
    ocean: "#4a5a9c",
    land: "#a8c39a",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "teacup",
    textureInk: "rgba(235,240,210,0.55)",
    textureInk2: "rgba(90,130,100,0.35)",
    coast: "#34466e",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(200,215,255,0.3)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(230,236,255,0.5)",
    lake: "#4a5a9c",
    ice: "#f4f2ea",
    relief: "rgba(52,70,110,0.45)",
    dot: "#fff8e6",
    dotStroke: "#34466e",
    fresh: "#e0493c",
    tuned: "#fff8e6",
    arc: "#e0493c",
    glow: false,
    atmosphere: "rgba(255,226,170,0.42)",
    shade: "rgba(30,30,80,0.45)",
    neatline: false,
    decor: null,
    scenery: "tea",
  },
  // A college campus in maroon and cream: maroon land on cream paper, varsity lettering, pennant buttons.
  campus: {
    id: "campus",
    label: "Campus",
    defaultView: "2d",
    projection2d: geoEqualEarth,
    ocean: "#f3ede1",
    land: "#881c1c",
    landTexture: "hatch",
    pixel: 1,
    dotShape: "shield",
    textureInk: "rgba(255,255,255,0.18)",
    coast: "#4e0d0d",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(136,28,28,0.25)",
    oceanHatch: null,
    graticule: "rgba(136,28,28,0.1)",
    graticuleDash: [],
    river: "rgba(243,237,225,0.4)",
    lake: "#f3ede1",
    ice: "#fbf8f1",
    relief: "rgba(255,255,255,0.35)",
    dot: "#ffffff",
    dotStroke: "#2a0808",
    fresh: "#f0b323",
    tuned: "#2a0808",
    arc: "#2a0808",
    glow: false,
    atmosphere: "rgba(136,28,28,0.25)",
    shade: "rgba(60,0,0,0.35)",
    neatline: false,
    decor: null,
  },
  // A trick roper's frontier: a denim sea with orange seams along every coast, tan leather land, a rope around the
  // sheet and spinning rope loops over the water (decision 69).
  lasso: {
    id: "lasso",
    label: "Lasso",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#46698c",
    land: "#c99a62",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "star6",
    textureInk: "rgba(240,205,150,0.4)",
    coast: "#4a2e16",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(74,46,22,0.3)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(70,105,140,0.7)",
    lake: "#46698c",
    ice: "#f1e7d2",
    relief: "rgba(90,55,25,0.7)",
    dot: "#fbf3df",
    dotStroke: "#3a2410",
    fresh: "#b3322a",
    tuned: "#3a2410",
    arc: "#b3322a",
    glow: false,
    atmosphere: "rgba(211,177,132,0.4)",
    shade: "rgba(60,30,0,0.35)",
    neatline: false,
    decor: null,
    scenery: "rope",
    textureInk2: "rgba(110,62,22,0.3)",
  },
  // Decision 70: three designs that draw the world a way of their own.
  // Night Drive: a 1980s night drive. The flat map is seen low over a black sea ruled by a glowing magenta grid,
  // receding to a horizon under a striped setting sun; land is a cyan wireframe with wire mountains.
  drive: {
    id: "drive",
    label: "Night Drive",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "neon",
    globeScale: 0.32,
    tilt: 66,
    tiltEye: 0.5,
    tiltFar: 0.3,
    tiltMinZoom: 1.4,
    sky: ["#0d0221", "#4a1068", "#ff7a3d"],
    fog: "#ff4f9a",
    ocean: "#07010f",
    land: "#0d0628",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(111,246,255,0.45)",
    coast: "#6ff6ff",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "#ff4fd8",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#07010f",
    ice: "#0d0628",
    relief: "#9ffbff",
    dot: "#ffe14d",
    dotStroke: "#1a0530",
    fresh: "#ff4fd8",
    tuned: "#ffffff",
    arc: "#6ff6ff",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Cross Stitch: an embroidered sampler. Land in X stitches on linen aida cloth, threads by climate and relief,
  // coasts in backstitch, the globe held in a wooden embroidery hoop, markers as sewn buttons.
  stitch: {
    id: "stitch",
    label: "Cross Stitch",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "stitch",
    globeScale: 0.32,
    ocean: "#efe6d2",
    land: "#6f9a4a",
    landTexture: "none",
    pixel: 1,
    dotShape: "button",
    textureInk: "rgba(120,96,60,0.28)",
    coast: "#4a3326",
    coastWidth: 1.6,
    waterlines: 0,
    waterline: "#a9c6db",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#efe6d2",
    ice: "#fbfaf5",
    relief: "#8a6040",
    dot: "#9e1f4a",
    dotStroke: "#f6efdd",
    fresh: "#1f6fd1",
    tuned: "#4a3326",
    arc: "#b0304a",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Rose Window: stained glass. Land and sea cut into pieces of jewel-toned glass held in dark lead, lit from
  // behind; the globe is the centre of a round window in stone tracery.
  glass: {
    id: "glass",
    label: "Rose Window",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "glass",
    globeScale: 0.27,
    ocean: "#1b3f8f",
    land: "#2f8a4a",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0)",
    coast: "#16121c",
    coastWidth: 3.2,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#1b3f8f",
    ice: "#dfe8f2",
    relief: "#7a4a9a",
    dot: "#fff4d2",
    dotStroke: "#16121c",
    fresh: "#ffc21a",
    tuned: "#fff4d2",
    arc: "#fff4d2",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // ---- Decision 71: three designs, each with its own camera ----
  // A club night: the globe is a mirror ball, the map a light-up dance floor under a tilted camera.
  club: {
    id: "club",
    label: "Nightclub",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    ocean: "#1b1530",
    land: "#6b2a8f",
    landTexture: "none",
    pixel: 1,
    tilt: 56,
    fog: "#1a0b2e",
    globeScale: 0.3,
    scene: "club",
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "rgba(0,0,0,0)",
    coastWidth: 0,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#1b1530",
    ice: "#cfd6ea",
    relief: "rgba(0,0,0,0)",
    dot: "#ffffff",
    dotStroke: "#12001c",
    fresh: "#ffe14d",
    tuned: "#ffffff",
    arc: "#5ff6ff",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Hollywood-hills noir: the map on a swimming pool's floor, the globe afloat at night under string lights.
  pool: {
    id: "pool",
    label: "Poolside",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2fb8c6",
    land: "#f7a8c4",
    landTexture: "none",
    pixel: 1,
    globeScale: 0.28,
    scene: "pool",
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#4a1f73",
    coastWidth: 1.4,
    waterlines: 0,
    waterline: "rgba(255,255,255,0.22)",
    oceanHatch: null,
    oceanPattern: "tiles",
    graticule: "rgba(255,255,255,0.18)",
    graticuleDash: [],
    river: "rgba(74,31,115,0.35)",
    lake: "#2fb8c6",
    ice: "#fde7ef",
    relief: "rgba(74,31,115,0.55)",
    dot: "#ffffff",
    dotStroke: "#3a1260",
    fresh: "#ffb300",
    tuned: "#3a1260",
    arc: "#3a1260",
    glow: false,
    atmosphere: null,
    shade: "rgba(20,10,60,0.4)",
    neatline: false,
    decor: null,
  },
  // A snow globe on a wooden base; the flat map is seen through curved glass.
  snow: {
    id: "snow",
    label: "Snow Globe",
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    ocean: "#b9d4e8",
    land: "#fbfaf5",
    landTexture: "none",
    pixel: 1,
    globeScale: 0.24,
    scene: "snow",
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#34506e",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(52,80,110,0.18)",
    oceanHatch: null,
    graticule: "rgba(52,80,110,0.2)",
    graticuleDash: [],
    river: "rgba(52,80,110,0.35)",
    lake: "#b9d4e8",
    ice: "#ffffff",
    relief: "rgba(52,80,110,0.5)",
    dot: "#1d3557",
    dotStroke: "#ffffff",
    fresh: "#d62839",
    tuned: "#1d3557",
    arc: "#1d3557",
    glow: false,
    atmosphere: null,
    shade: "rgba(40,70,110,0.35)",
    neatline: false,
    decor: null,
  },
  // A warehouse rave seen from the DJ booth: the map on the LED wall behind the decks, the globe a round screen
  // hung over the stage, lasers and beams sweeping slowly round them in UV and acid colours (src/map/scenes.ts).
  rave: {
    id: "rave",
    label: "Rave",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    ocean: "#0b0322",
    land: "#2c0d68",
    landTexture: "none",
    pixel: 1,
    globeScale: 0.34,
    scene: "rave",
    dotShape: "diamond",
    textureInk: "rgba(0,0,0,0)",
    coast: "#c6ff3a",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(255,63,212,0.16)",
    graticuleDash: [],
    river: "rgba(63,240,255,0.35)",
    lake: "#0b0322",
    ice: "#d8d0ff",
    relief: "rgba(198,255,58,0.3)",
    dot: "#f4ff4a",
    dotStroke: "#12002a",
    fresh: "#ff3fd4",
    tuned: "#ffffff",
    arc: "#3ff0ff",
    glow: false,
    atmosphere: null,
    shade: "rgba(10,0,30,0.45)",
    neatline: false,
    decor: null,
  },
  // Decision 74: four designs that borrow the feel of familiar things and name none of them.
  // Spreadsheet: the world as filled cells in a grid, shaded like conditional formatting by relief; the globe is a
  // chart object on the sheet (src/map/sheet.ts).
  sheet: {
    id: "sheet",
    label: "Spreadsheet",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "sheet",
    globeScale: 0.34,
    ocean: "#dbe8f7",
    land: "#a3d18b",
    landTexture: "none",
    pixel: 1,
    dotShape: "square",
    textureInk: "rgba(0,0,0,0)",
    coast: "#3f6b50",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "#e1e3e6",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#ffffff",
    ice: "#e6edf5",
    relief: "#3f7d47",
    dot: "#24313d",
    dotStroke: "#ffffff",
    fresh: "#1f63d1",
    tuned: "#2d8653",
    arc: "#2d8653",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Market Terminal: amber on black, the land as a dot-matrix plot over a coordinate grid, the globe a vector plot
  // in a ring of ticks (src/map/terminal.ts). No prices, no arrows, no red or green.
  terminal: {
    id: "terminal",
    label: "Market Terminal",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "terminal",
    globeScale: 0.4,
    ocean: "#030303",
    land: "rgba(255,176,0,0.07)",
    landTexture: "none",
    pixel: 1,
    dotShape: "block",
    textureInk: "rgba(255,176,0,0.62)",
    coast: "#ffb000",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(255,176,0,0.16)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#030303",
    ice: "rgba(255,230,190,0.1)",
    relief: "#ffd36b",
    dot: "#f4f4f4",
    dotStroke: "#030303",
    fresh: "#52c7ff",
    tuned: "#ffe066",
    arc: "#ffe066",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Country Club: preppy heritage clothing. The flat map is embroidered on oxford cloth, land in hunter green satin
  // stitch with a stitched edge; the globe is a leather desk globe tooled in gold on a brass stand (src/map/club.ts).
  prep: {
    id: "prep",
    label: "Country Club",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "club",
    globeScale: 0.29,
    ocean: "#c9d7e8",
    land: "#2f5b3f",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(255,255,255,0.13)",
    textureInk2: "rgba(0,0,0,0.16)",
    coast: "#1b3526",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "#f7f4ec",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#c9d7e8",
    ice: "#f1ead6",
    relief: "#8fb07a",
    dot: "#c9a043",
    dotStroke: "#1d2b4f",
    fresh: "#f6f1e4",
    tuned: "#1d2b4f",
    arc: "#b3262e",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Sleeper Car: a modern long-distance train's on-board route display. A navy screen with slate land, a silver
  // coast and the Equator, tropics and polar circles as red, blue and silver route lines across the sea; the globe
  // in a fine dial on the same screen (src/map/rail.ts). Markers are station dots.
  rail: {
    id: "rail",
    label: "Sleeper Car",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "rail",
    globeScale: 0.34,
    ocean: "#0c1c36",
    land: "#1f3659",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#a9bbd2",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(150,180,225,0.08)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#0c1c36",
    ice: "#3a5379",
    relief: "rgba(175,198,228,0.4)",
    dot: "#f4f8fd",
    dotStroke: "#0a1830",
    fresh: "#ff5566",
    tuned: "#ffffff",
    arc: "#8cb8ff",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Decision 77: two designs that move a little on their own.
  // Aquarium: the map is the back wall of a tank with gravel and plants below it and fish in open water; the globe
  // floats in a round fishbowl with a sloshing waterline, rising bubbles and fish swimming round it.
  aquarium: {
    id: "aquarium",
    label: "Aquarium",
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    surface: "aquarium",
    globeScale: 0.29,
    ocean: "#1f8a9e",
    land: "#d9c48f",
    landTexture: "none",
    pixel: 1,
    dotShape: "shell",
    textureInk: "rgba(120,96,50,0.35)",
    textureInk2: "rgba(96,140,70,0.3)",
    coast: "#3f5a36",
    coastWidth: 1.1,
    waterlines: 0,
    waterline: "rgba(190,250,240,0.4)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#1f8a9e",
    ice: "#eef7f4",
    relief: "#8a7a52",
    dot: "#12324a",
    dotStroke: "#fff8e8",
    fresh: "#ff7a1a",
    tuned: "#12324a",
    arc: "#fff8e8",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Lava Lamp: a 1970s lava lamp. Warm wax drifts slowly through the dark liquid of the sea behind glowing land; on
  // the globe the world is the lamp's glass on a metal base, with a cap on top.
  lava: {
    id: "lava",
    label: "Lava Lamp",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    surface: "lava",
    globeScale: 0.215,
    ocean: "#1c1240",
    land: "#ffd98a",
    landTexture: "none",
    pixel: 1,
    dotShape: "squircle",
    textureInk: "rgba(255,240,200,0.5)",
    coast: "#b4501c",
    coastWidth: 1.1,
    waterlines: 0,
    waterline: "rgba(255,170,70,0.3)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#1c1240",
    ice: "#fff3d6",
    relief: "#e8a04a",
    dot: "#139f93",
    dotStroke: "#1a0d2e",
    fresh: "#ffffff",
    tuned: "#1a0d2e",
    arc: "#fff3d6",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Decision 75: four screens and cameras, each drawn in its own file.
  // Radar Sweep: a round weather-radar scope. Land as phosphor speckle, range rings on the reticle, a slow beam.
  radar: {
    id: "radar",
    label: "Radar Sweep",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "radar",
    globeScale: 0.37,
    motion: true,
    pinRing: true,
    ocean: "#03140b",
    land: "#0a2a19",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(120,255,170,0.5)",
    coast: "#78ffaa",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#03140b",
    ice: "#0a2a19",
    relief: "#78ffaa",
    dot: "#c8ffdc",
    dotStroke: "#021008",
    fresh: "#ffc44d",
    tuned: "#eafff2",
    arc: "#c8ffdc",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Film Noir: a black-and-white 1940s detective film. The map lies on a desk under a canted camera, in a lamp's
  // pool of light, with the shadows of blinds across it.
  noir: {
    id: "noir",
    label: "Film Noir",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "noir",
    warp: "desk",
    globeScale: 0.4,
    ocean: "#2b2b29",
    land: "#9a9892",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0.3)",
    coast: "#f2f0e8",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(242,240,232,0.14)",
    oceanHatch: null,
    graticule: "rgba(242,240,232,0.1)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#2b2b29",
    ice: "#c9c7c0",
    relief: "#1c1c1a",
    dot: "#f6f4ec",
    dotStroke: "#111110",
    fresh: "#f6f4ec",
    tuned: "#ffffff",
    arc: "rgba(246,244,236,0.85)",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Arcade Cabinet: the map on a curved picture tube in an arcade cabinet, glowing vector coastlines, scanlines.
  arcade: {
    id: "arcade",
    label: "Arcade Cabinet",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "arcade",
    warp: "barrel",
    motion: true,
    globeScale: 0.4,
    ocean: "#04030b",
    land: "#171445",
    landTexture: "none",
    pixel: 1,
    dotShape: "diamond",
    textureInk: "rgba(120,170,255,0.35)",
    coast: "#c4ecff",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(80,120,255,0.16)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#04030b",
    ice: "#0d0b26",
    relief: "#8fd0ff",
    dot: "#ffe03d",
    dotStroke: "#1b1000",
    fresh: "#54f0ff",
    tuned: "#ffffff",
    arc: "#ffe03d",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Stadium Jumbotron: the map on a giant screen seen from the stands, LED pixels, floodlights and a crowd.
  stadium: {
    id: "stadium",
    label: "Stadium Jumbotron",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "stadium",
    warp: "stadium",
    motion: true,
    globeScale: 0.4,
    ocean: "#0a2a66",
    land: "#2f9a5a",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0.2)",
    coast: "#d9f6ff",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(140,200,255,0.18)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#0a2a66",
    ice: "#e6f2fa",
    relief: "#1f6b3d",
    dot: "#ffd23a",
    dotStroke: "#241400",
    fresh: "#ff4fb0",
    tuned: "#ffffff",
    arc: "#ffd23a",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Pop-up Book (decision 76, src/map/popup.ts): the continents are thick paper cut-outs standing up off the page
  // of a children's pop-up book. Zooming out lays the page flatter, zooming in stands it up.
  popup: {
    id: "popup",
    label: "Pop-up Book",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "popup",
    globeScale: 0.4,
    tilt: 54,
    tiltOut: [24, 3.4],
    tiltEye: 1.15,
    tiltFar: 0.6,
    tiltMinZoom: 1,
    ocean: "#8fd0ee",
    land: "#8ccd5c",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(255,255,255,0.5)",
    coast: "#2f6b34",
    coastWidth: 1,
    waterlines: 0,
    waterline: "#c4e9f8",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#8fd0ee",
    ice: "#f7fbff",
    relief: "#9a6b45",
    dot: "#2f4fc9",
    dotStroke: "#ffffff",
    fresh: "#ffbf1a",
    tuned: "#1d2440",
    arc: "#1d2440",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Toy Train Set (decision 76, src/map/trainset.ts): a model railway on a tabletop, seen from above at an angle:
  // green felt land, painted mountains, model trees, and toy trains running round oval tracks out at sea.
  trainset: {
    id: "trainset",
    label: "Toy Train Set",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "trainset",
    globeScale: 0.33,
    tilt: 52,
    tiltEye: 2.6,
    tiltFar: 0.6,
    tiltMinZoom: 1.3,
    ocean: "#4f9ccb",
    land: "#5f9b3d",
    landTexture: "none",
    pixel: 1,
    dotShape: "house",
    textureInk: "rgba(255,255,255,0.3)",
    coast: "#7a5a3a",
    coastWidth: 1,
    waterlines: 0,
    waterline: "#e6d3a0",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#4f9ccb",
    ice: "#f4f7f8",
    relief: "#8a7460",
    dot: "#fbf4e4",
    dotStroke: "#3a2a1c",
    fresh: "#ffb81f",
    tuned: "#fbf4e4",
    arc: "#fbf4e4",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Chalkboard (decision 76, src/map/chalk.ts): the world drawn in chalk on a classroom board, the globe a chalk
  // circle with hatching; dragging leaves a faint smudge that fades.
  chalk: {
    id: "chalk",
    label: "Chalkboard",
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    surface: "chalk",
    globeScale: 0.42,
    ocean: "#26362e",
    land: "#26362e",
    landTexture: "none",
    pixel: 1,
    dotShape: "loop",
    textureInk: "rgba(240,238,228,0.3)",
    coast: "#f3f0e6",
    coastWidth: 2,
    waterlines: 0,
    waterline: "rgba(240,238,228,0.12)",
    oceanHatch: null,
    graticule: "rgba(240,238,228,0.16)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#26362e",
    ice: "#26362e",
    relief: "rgba(240,238,228,0.55)",
    dot: "#f5f2e8",
    dotStroke: "#22302a",
    fresh: "#ffd84d",
    tuned: "#ff9ec4",
    arc: "#ff9ec4",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Sketchbook (decision 76, src/map/sketch.ts): a pencil sketch on paper. Wobbly coasts redrawn a little
  // differently a few times a second, cross-hatched land, graphite and a touch of watercolour for the sea.
  sketch: {
    id: "sketch",
    label: "Sketchbook",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "sketch",
    globeScale: 0.42,
    ocean: "#f6f1e6",
    land: "#f6f1e6",
    landTexture: "none",
    pixel: 1,
    dotShape: "loop",
    textureInk: "rgba(52,52,60,0.34)",
    coast: "#2f2f36",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "#7fb0dc",
    oceanHatch: null,
    graticule: "rgba(47,47,54,0.12)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#f6f1e6",
    ice: "#f6f1e6",
    relief: "rgba(47,47,54,0.6)",
    dot: "#2f2f36",
    dotStroke: "#f6f1e6",
    fresh: "#1f5fd6",
    tuned: "#1f5fd6",
    arc: "#1f5fd6",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Couch Potato (id cube): the clean, glossy menus of late-2000s home consoles in the chrome, and inside the map an
  // old news channel's Earth in dark blue space (src/map/gloss.ts, decision 104). No console maker's names, logos,
  // menus or characters.
  cube: {
    id: "cube",
    label: "Couch Potato",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "gloss",
    globeScale: 0.42,
    ocean: "#1c5fae",
    land: "#4d8a3c",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "#3c6e30",
    coast: "rgba(18,52,30,0.4)",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(96,176,236,0.42)",
    oceanHatch: null,
    graticule: "rgba(255,255,255,0.1)",
    graticuleDash: [],
    river: "rgba(64,140,214,0.75)",
    lake: "#3f8ad6",
    ice: "#f2f7fb",
    relief: "rgba(96,74,44,0.55)",
    dot: "#3fa9f5",
    dotStroke: "#ffffff",
    fresh: "#ffa62b",
    tuned: "#ffd64a",
    arc: "rgba(255,255,255,0.85)",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Undersea Town: after the feel of a bright cartoon sea floor, with no characters, dwellings or names. Turquoise
  // water lit from above, sandy seabed land with a pale lagoon along the coasts, and in tested open sea flower-shaped
  // clouds, jellyfish and little reef gardens, all drawn for this site (src/map/scenery.ts). Bubbles, the seabed and
  // the wooden sign are chrome (style.css).
  reef: {
    id: "reef",
    label: "Undersea Town",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#1fb2c6",
    land: "#f1d596",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(255,241,204,0.75)",
    textureInk2: "rgba(200,152,84,0.5)",
    coast: "#8a5a26",
    coastWidth: 1.8,
    waterlines: 0,
    waterline: "rgba(220,252,255,0.4)",
    oceanHatch: null,
    shallows: "#6ddbd6",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(31,178,198,0.8)",
    lake: "#1fb2c6",
    ice: "#fff6e2",
    relief: "rgba(150,100,48,0.55)",
    dot: "#48237a",
    dotStroke: "#ffffff",
    fresh: "#ff4f86",
    tuned: "#ff4f86",
    arc: "#ff4f86",
    glow: false,
    atmosphere: "rgba(170,245,255,0.55)",
    shade: "rgba(0,60,90,0.35)",
    neatline: false,
    decor: null,
    scenery: "reef",
  },
  // Block World: after the feel of a blocky sandbox game, with none of its characters, names or art. The world as
  // square blocks with one pixel texture per kind: grass, sand, stone, snow, and translucent water, with dirt showing
  // on the front faces (src/map/blocks.ts); a sky with square clouds around it; a hotbar toolbar and grey
  // inventory panels.
  blocks: {
    id: "blocks",
    label: "Block World",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "blocks",
    ocean: "#2f5fcf",
    land: "#63a83a",
    landTexture: "none",
    pixel: 2,
    dotShape: "square",
    textureInk: "rgba(0,0,0,0)",
    coast: "#3b2a16",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(255,255,255,0.1)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#2f5fcf",
    ice: "#f2f6fa",
    relief: "#6c6c6c",
    dot: "#ffffff",
    dotStroke: "#1b1b1b",
    fresh: "#ff3b30",
    tuned: "#ffe14a",
    arc: "#ffe14a",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Dual Screen (id dual): a two-screen handheld from the mid-2000s. The word and the stories on one screen, the map
  // on the touch screen, drawn at a low resolution in crisp pixels. No maker's names, logos, menus or characters.
  dual: {
    id: "dual",
    label: "Dual Screen",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#2f86e0",
    land: "#98d65a",
    landTexture: "dither",
    pixel: 2,
    dotShape: "square",
    textureInk: "#6cbc3e",
    coast: "#173f26",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(255,255,255,0.3)",
    oceanHatch: null,
    shallows: "#4ea2ec",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#4ea2ec",
    lake: "#4ea2ec",
    ice: "#f4f8ff",
    relief: "#5a7a2a",
    dot: "#ffffff",
    dotStroke: "#16203a",
    fresh: "#ff4f3a",
    tuned: "#ffd23a",
    arc: "#ffd23a",
    glow: false,
    atmosphere: "rgba(160,205,255,0.5)",
    shade: "rgba(0,20,70,0.4)",
    neatline: false,
    decor: null,
  },
  // Old Realm: an early-2000s fantasy online game's world map, after the look only. A muddy painted land of greens
  // and browns on blue water, seen in Map view through a round minimap window in carved stone with a compass rose;
  // small shields for markers. No game's name, icons or artwork.
  realm: {
    id: "realm",
    // A no-break space keeps both words on a phone, where the menu shows a label's first word only.
    label: "Old\u00a0Realm",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    minimap: true,
    ocean: "#35647d",
    land: "#6f7f45",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "shield",
    textureInk: "rgba(122,92,48,0.55)",
    textureInk2: "rgba(150,168,84,0.5)",
    coast: "#3a2c16",
    coastWidth: 1.3,
    waterlines: 1,
    waterline: "rgba(196,222,214,0.2)",
    oceanHatch: null,
    oceanPattern: "mottle",
    shallows: "#4d7f8e",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(120,176,196,0.8)",
    lake: "#35647d",
    ice: "#e6e2cf",
    relief: "rgba(58,40,18,0.62)",
    dot: "#f4d24c",
    dotStroke: "#2a1a08",
    fresh: "#62e3f0",
    tuned: "#fff4c2",
    arc: "#f4d24c",
    glow: false,
    atmosphere: "rgba(240,210,140,0.35)",
    shade: "rgba(30,20,8,0.5)",
    neatline: false,
    decor: null,
  },
  // Tactical: an overhead radar in a competitive team game's HUD, after the look only. Desaturated greys and olive
  // on a faint grid, a clock since the map was built and a feed of the newest headlines around it (src/ui/extras.ts).
  // Nothing martial, no game's name or logo, and a pinned place gets a ring, never a square frame.
  tactical: {
    id: "tactical",
    label: "Tactical",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    pinRing: true,
    ocean: "#262927",
    land: "#5a5f4c",
    landTexture: "none",
    pixel: 1,
    dotShape: "diamond",
    textureInk: "rgba(0,0,0,0)",
    coast: "#c5c8b8",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(205,210,195,0.08)",
    oceanHatch: null,
    oceanPattern: "tiles",
    graticule: "rgba(205,210,195,0.13)",
    graticuleDash: [],
    river: "rgba(160,170,160,0.35)",
    lake: "#262927",
    ice: "#7d8078",
    relief: "rgba(34,36,30,0.55)",
    dot: "#eeeee6",
    dotStroke: "#141614",
    fresh: "#ff9d1e",
    tuned: "#ffd23f",
    arc: "#ffd23f",
    glow: false,
    atmosphere: null,
    shade: "rgba(0,0,0,0.5)",
    neatline: false,
    decor: null,
  },
  // Pin Drop: after the feel of geography guessing games, where a player is dropped somewhere, drops a pin on a
  // small map and is scored by distance; none of any game's names, logos, pins or art. A clean road-map palette with
  // pale land and soft blue water, indigo map pins, a bold HUD over the map with the reticle's position and a scale
  // bar (src/ui/extras.ts), and a compass. Nothing is scored: the HUD measures the map, never a place or a story.
  pindrop: {
    id: "pindrop",
    // A no-break space keeps both words on a phone, where the menu shows a label's first word only.
    label: "Pin\u00a0Drop",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#9ccfe6",
    land: "#eef0e2",
    landTexture: "none",
    pixel: 1,
    dotShape: "pin",
    textureInk: "rgba(0,0,0,0)",
    coast: "#86b8cf",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(255,255,255,0.3)",
    oceanHatch: null,
    shallows: "#b6deee",
    graticule: "rgba(255,255,255,0.35)",
    graticuleDash: [],
    river: "rgba(120,180,210,0.9)",
    lake: "#9ccfe6",
    ice: "#fbfcfd",
    relief: "rgba(104,138,92,0.32)",
    dot: "#4a2ab8",
    dotStroke: "#ffffff",
    fresh: "#f2384f",
    tuned: "#1c1050",
    arc: "#f28a00",
    glow: false,
    atmosphere: "rgba(190,230,255,0.55)",
    shade: "rgba(20,30,80,0.3)",
    neatline: false,
    decor: null,
  },
  // Deli Counter: a sandwich shop's counter, after no shop in particular. Cream deli paper for land on brown butcher
  // paper for the sea, inked like a stamp; tomato-red order tickets for markers, pickle green for fresh reports. The
  // chrome is a chalkboard menu board, a striped awning, white wall tiles and order pads (style.css).
  deli: {
    id: "deli",
    label: "Deli Counter",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#c9a271",
    land: "#fbf5e6",
    landTexture: "halftone",
    pixel: 1,
    dotShape: "ticket",
    textureInk: "rgba(110,65,32,0.17)",
    coast: "#6e4120",
    coastWidth: 1.2,
    waterlines: 2,
    waterline: "rgba(96,58,26,0.22)",
    oceanHatch: "rgba(96,58,26,0.07)",
    graticule: "rgba(96,58,26,0.14)",
    graticuleDash: [3, 4],
    river: "rgba(110,65,32,0.4)",
    lake: "#c9a271",
    ice: "#fffdf6",
    relief: "rgba(110,65,32,0.5)",
    dot: "#c4321f",
    dotStroke: "#fffaf0",
    fresh: "#2f7d32",
    tuned: "#2a1a0e",
    arc: "#2a1a0e",
    glow: false,
    atmosphere: null,
    shade: "rgba(80,45,15,0.3)",
    neatline: false,
    decor: null,
  },
  // Marquee: a picture house, after no cinema chain or studio. The map is the silver screen in a dark auditorium,
  // framed by red velvet curtains (style.css): silver land on a black sea, like a black-and-white picture, with
  // butter-yellow ticket stubs for markers and a warm projector glow round the globe. Bulb-lit marquee lettering, a
  // letter board for the word and a film strip for the time bar.
  marquee: {
    id: "marquee",
    label: "Marquee",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#101118",
    land: "#8d8a84",
    landTexture: "dither",
    pixel: 1,
    dotShape: "stub",
    textureInk: "#9a978f",
    coast: "#ece6d8",
    coastWidth: 1,
    waterlines: 1,
    waterline: "rgba(236,230,216,0.1)",
    oceanHatch: null,
    graticule: "rgba(236,230,216,0.07)",
    graticuleDash: [],
    river: "rgba(16,17,24,0.6)",
    lake: "#101118",
    ice: "#c9c5bc",
    relief: "rgba(24,22,20,0.5)",
    dot: "#ffc83a",
    dotStroke: "#1a0d08",
    fresh: "#ff5c7a",
    tuned: "#fff4d6",
    arc: "#ffc83a",
    glow: false,
    atmosphere: "rgba(255,214,150,0.28)",
    shade: "rgba(0,0,0,0.55)",
    neatline: false,
    decor: null,
  },
  // Gummy Cluster: after sweets where a soft gummy centre is coated in a crust of tiny crunchy candy bits, after no
  // brand in particular. The land is the crust: bits in many bright colours, cut once from a fixed seed and tiled the
  // same over all land (`crunch`), over a pink gummy body that shows as a glossy rim along every coast. The sea is a
  // clear blue gummy with a gloss. No land is red; cherry red belongs to fresh reports. Rounded nugget markers in dark
  // plum with a white edge read on the busy crust and on the sea.
  crunch: {
    id: "crunch",
    label: "Gummy Cluster",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#86d4dd",
    land: "#ff8cc0",
    landTexture: "crunch",
    pixel: 1,
    dotShape: "nugget",
    textureInk: "rgba(58,16,72,0.45)",
    textureInk2: "rgba(255,255,255,0.8)",
    coast: "#6a2d72",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(255,255,255,0.55)",
    oceanHatch: null,
    oceanPattern: "shimmer",
    shallows: "rgba(255,105,180,0.38)",
    graticule: "rgba(30,90,120,0.12)",
    graticuleDash: [],
    river: "rgba(40,120,150,0.75)",
    lake: "#86d4dd",
    ice: "#fff4fb",
    relief: "rgba(255,255,255,0.62)",
    dot: "#2a0b46",
    dotStroke: "#ffffff",
    fresh: "#e8173a",
    tuned: "#ffffff",
    arc: "#ffe14d",
    glow: false,
    atmosphere: "rgba(255,140,205,0.4)",
    shade: "rgba(40,10,80,0.42)",
    neatline: false,
    decor: null,
  },
  // Crystal Towers, experimental: after the feel of an early-2000s black console's system menu (src/map/towers.ts). The
  // world floats in a dark blue void over a reflective floor where towers of clear cubes stand and rise slowly, all
  // decoration and never data. Pale blue land on dark glass, white diamonds, warm amber for fresh reports.
  towers: {
    id: "towers",
    label: "Crystal Towers",
    experimental: true,
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    surface: "towers",
    globeScale: 0.34,
    ocean: "#0b1a3a",
    land: "#4f78b8",
    landTexture: "none",
    pixel: 1,
    dotShape: "diamond",
    textureInk: "rgba(0,0,0,0)",
    coast: "#dcecff",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(130,185,255,0.26)",
    oceanHatch: null,
    graticule: "rgba(140,190,255,0.1)",
    graticuleDash: [],
    river: "rgba(160,205,255,0.4)",
    lake: "#0b1a3a",
    ice: "#dcecff",
    relief: "rgba(0,0,0,0)",
    dot: "#f2f8ff",
    dotStroke: "#06102a",
    fresh: "#ffb547",
    tuned: "#ffffff",
    arc: "rgba(205,228,255,0.85)",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Green Core (experimental): after the feel of an early-2000s black and green console dashboard, with
  // no maker's or console's name, logo, shapes, sounds or art. The globe is a glowing orb with energy turning slowly in
  // its dark green glass, lit green land, a halo and lit tubes curving through the dark room behind it; the map is a
  // dark green panel in a bezel that is itself a lit tube (src/map/core.ts). Near-white markers that glow, amber for
  // fresh reports, so neither reads as the green of the picture.
  core: {
    id: "core",
    label: "Green Core",
    experimental: true,
    defaultView: "3d",
    projection2d: geoEqualEarth,
    surface: "core",
    globeScale: 0.34,
    ocean: "#062c16",
    land: "#3ece62",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(150,255,175,0.3)",
    coast: "rgba(185,255,200,0.85)",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "rgba(70,255,120,0.12)",
    oceanHatch: null,
    graticule: "rgba(90,255,130,0.07)",
    graticuleDash: [],
    river: "rgba(10,60,28,0.6)",
    lake: "#062c16",
    ice: "#6ec882",
    relief: "rgba(200,255,210,0.12)",
    dot: "#f2fff5",
    dotStroke: "#03200d",
    fresh: "#ffb21e",
    tuned: "#ffffff",
    arc: "rgba(242,255,245,0.85)",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // After the feel of an early-2000s cube console's menu: the world on a glossy purple cube that unfolds into its net
  // (src/map/fold.ts). Experimental: opened only by a link until it is listed (decision 105).
  fold: {
    id: "fold",
    label: "Folding Cube",
    experimental: true,
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "fold",
    ocean: "#3b2394",
    land: "#a993f4",
    landTexture: "none",
    pixel: 1,
    dotShape: "cube",
    textureInk: "rgba(255,255,255,0.3)",
    coast: "#f1ebff",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(150,126,240,0.35)",
    oceanHatch: null,
    shallows: "rgba(126,98,226,0.55)",
    graticule: "rgba(196,178,255,0.16)",
    graticuleDash: [],
    river: "rgba(59,35,148,0.55)",
    lake: "#3b2394",
    ice: "#e9e2ff",
    relief: "rgba(255,255,255,0.5)",
    dot: "#ffffff",
    dotStroke: "#1f1250",
    fresh: "#ffa21f",
    tuned: "#ffffff",
    arc: "#ffd27a",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Machine Music, experimental: after the feel of 1970s and 80s German electronic music stage shows and constructivist
  // posters (src/map/machine.ts). The world as a vector display: a black screen under a fine red grid, or a red
  // wireframe sphere on a stage of lit grid panels with one red diagonal; land ruled in grey scan lines, coasts as neon
  // tubes. Square red pads with a dark edge, white for fresh reports. Black, signal red, warm grey and white only.
  machine: {
    id: "machine",
    label: "Machine Music",
    experimental: true,
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "machine",
    globeScale: 0.36,
    ocean: "#0b0b0a",
    land: "#4b4b47",
    landTexture: "none",
    pixel: 1,
    dotShape: "square",
    textureInk: "rgba(0,0,0,0)",
    coast: "#ff3a2f",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "rgba(215,25,32,0.2)",
    oceanHatch: null,
    graticule: "rgba(215,25,32,0.3)",
    graticuleDash: [],
    river: "rgba(5,5,5,0.6)",
    lake: "#0b0b0a",
    ice: "#85857f",
    relief: "rgba(214,214,204,0.22)",
    dot: "#e8232a",
    dotStroke: "#0a0a0a",
    fresh: "#f4f4ee",
    tuned: "#ffffff",
    arc: "rgba(232,232,224,0.8)",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // First Render: after the feel of the first computer-animated music videos of the mid-1980s
  // (src/map/render.ts). The world as untextured flat-shaded polygons under one hard light: a low-poly ball in a room
  // of teal wallpaper and checked floor, or flat facets on a screen in a two-tone bevel. White gem markers, tomato red
  // for fresh reports.
  render: {
    id: "render",
    label: "First Render",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "render",
    globeScale: 0.36,
    ocean: "#2a4fc0",
    land: "#3fae4a",
    landTexture: "none",
    pixel: 1,
    dotShape: "diamond",
    textureInk: "rgba(0,0,0,0)",
    coast: "#16204f",
    coastWidth: 1.1,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#2f58cc",
    lake: "#2f58cc",
    ice: "#e8f4ee",
    relief: "rgba(0,0,0,0)",
    dot: "#ffffff",
    dotStroke: "#16204f",
    fresh: "#e8372a",
    tuned: "#ffffff",
    arc: "#f0c537",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Departures (experimental): after the feel of a split-flap departures board in a big station hall, with no
  // operator's, airline's, railway's or maker's names, logos or colours. The map is the hall's wall map, a deep
  // blue-green sheet with land as cream dots and thin pale-blue coasts; the globe sits in a round hall clock's ring of
  // ticks (src/map/flap.ts). Small square lamps for markers, warm white with an orange lamp for fresh reports, so
  // neither reads as the blue of the coasts. No amber or yellow anywhere: that is Market Terminal's.
  flap: {
    id: "flap",
    label: "Departures",
    experimental: true,
    defaultView: "2d",
    projection2d: geoEqualEarth,
    surface: "flap",
    globeScale: 0.4,
    ocean: "#15252c",
    land: "#1e3139",
    landTexture: "none",
    pixel: 1,
    dotShape: "square",
    textureInk: "rgba(246,240,221,0.62)",
    coast: "#6fa8cf",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(111,168,207,0.1)",
    oceanHatch: null,
    graticule: "rgba(246,240,221,0.06)",
    graticuleDash: [],
    river: "rgba(21,37,44,0.8)",
    lake: "#15252c",
    ice: "rgba(246,240,221,0.3)",
    relief: "rgba(255,248,226,0.88)",
    dot: "#fff6df",
    dotStroke: "#0a1519",
    fresh: "#ff7a1a",
    tuned: "#ffffff",
    arc: "rgba(143,196,238,0.85)",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Desktop 95: after the feel of a mid-1990s desktop operating system, with no maker's or product's
  // name, logo, sounds or art. The site is a teal desktop of windows (src/ui/desktop.ts); the map is drawn as an old
  // program would, in sixteen colours with dithered shallows and shading, at half resolution (src/map/desktop.ts).
  desktop: {
    id: "desktop",
    label: "Desktop 95",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "desktop",
    ocean: "#000080",
    land: "#008000",
    landTexture: "none",
    pixel: 2,
    dotShape: "square",
    textureInk: "rgba(0,0,0,0)",
    coast: "#000000",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "#0000ff",
    graticuleDash: [],
    river: "#0000ff",
    lake: "#000080",
    ice: "#ffffff",
    relief: "#808000",
    dot: "#ffffff",
    dotStroke: "#000000",
    fresh: "#ff0000",
    tuned: "#ffff00",
    arc: "#ffff00",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Record Player, experimental: after the feel of a 1970s home turntable (src/map/vinyl.ts). Globe view is the
  // record seen from above, the world on it round the North Pole at the spindle, turning under the tonearm whose
  // needle is the reticle; Map view is the sleeve's back, printed in brown ink. Cream land on black vinyl, orange
  // label-like dots that read on the vinyl, the cream land and the sleeve's ink alike, sky blue for fresh reports.
  vinyl: {
    id: "vinyl",
    label: "Record Player",
    experimental: true,
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    surface: "vinyl",
    globeScale: 0.44,
    ocean: "#0d0c0d",
    land: "#d9c8a2",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#8a6a45",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(255,250,240,0.06)",
    oceanHatch: null,
    graticule: "rgba(255,250,240,0.06)",
    graticuleDash: [],
    river: "rgba(110,82,50,0.45)",
    lake: "#0d0c0d",
    ice: "#aba498",
    relief: "rgba(0,0,0,0)",
    dot: "#ff7a1f",
    dotStroke: "#1b0f06",
    fresh: "#52c8ff",
    tuned: "#fff3dc",
    arc: "#ef7d2e",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Paper Screen, experimental: after the feel of an e-ink reading device (src/map/paper.ts, src/ui/paper.ts). Greys only
  // from one sixteen-step ramp, ink to a warm paper white: white sea with fine water lines, stippled mid-grey land,
  // black coasts. Black circle markers; fresh reports get the dotted ring, so nothing needs a colour.
  paper: {
    id: "paper",
    label: "Paper Screen",
    experimental: true,
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "paper",
    ocean: "#f5f3ee",
    land: "#acaba7",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "#474543",
    coast: "#1b1a18",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "#acaba7",
    oceanHatch: null,
    graticule: "#c9c8c3",
    graticuleDash: [1, 3],
    river: "#8f8e8a",
    lake: "#f5f3ee",
    ice: "#e6e5e0",
    relief: "#474543",
    dot: "#1b1a18",
    dotStroke: "#f5f3ee",
    fresh: "#1b1a18",
    tuned: "#1b1a18",
    arc: "#474543",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Shortwave, experimental: after the feel of a mid-century world-band radio receiver. The world drawn like an old
  // radio's dial map, cream paper land on a sepia-green sea with thin brown coasts and a faint grid, and on the globe
  // the same ball lit warm from behind. The page tunes it with a dial and a knob under the map (src/ui/dial.ts, laid
  // out by src/map/shortwave.ts). Amber dial-lamp dots, red for fresh reports.
  shortwave: {
    id: "shortwave",
    label: "Shortwave",
    experimental: true,
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#a3ab86",
    land: "#f1e6c6",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#6a4526",
    coastWidth: 0.8,
    waterlines: 2,
    waterline: "rgba(74,58,30,0.16)",
    oceanHatch: null,
    graticule: "rgba(84,58,30,0.26)",
    graticuleDash: [],
    river: "rgba(84,104,86,0.55)",
    lake: "#a3ab86",
    ice: "#f8f2df",
    relief: "rgba(106,69,38,0.42)",
    dot: "#e68a1c",
    dotStroke: "#3a220f",
    fresh: "#d0321f",
    tuned: "#b3221a",
    arc: "rgba(179,34,26,0.7)",
    glow: true,
    atmosphere: "rgba(255,196,112,0.62)",
    shade: "rgba(74,46,20,0.34)",
    neatline: false,
    decor: null,
  },
  // Postcards: after the feel of travel postcards on a wire rack in a corner shop (src/map/postcard.ts,
  // src/ui/postcard.ts). A folded paper travel map, cream land on pale blue sea with the sheet's creases, or a paper
  // globe printed in gores; the place's panel is a postcard that turns over. Airmail red circles with a cream edge,
  // airmail blue for fresh reports.
  postcard: {
    id: "postcard",
    label: "Postcards",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "postcard",
    globeScale: 0.4,
    ocean: "#c6dfe6",
    land: "#f2e6c8",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#6d8796",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(77,118,140,0.22)",
    graticuleDash: [3, 3],
    river: "#86b4c7",
    lake: "#c6dfe6",
    ice: "#fbf8ef",
    relief: "rgba(122,92,58,0.42)",
    dot: "#c8352d",
    dotStroke: "#fbf6ea",
    fresh: "#2457a8",
    tuned: "#2b2118",
    arc: "rgba(36,87,168,0.85)",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Zine: after the feel of a zine printed on a stencil duplicator in spot inks on recycled paper,
  // a little out of register, and none of any maker's, shop's or zine's names, logos or art (src/map/zine.ts). Land
  // in a blue halftone, coasts in pink printed a pixel or two off, pink dots in the shallows, bare paper sea. Pink
  // markers with a blue outline printed off register (view.ts), yellow for fresh reports. Plate carree, so a drag
  // moves every point of the map by the same amount and the dot screens can travel with the land exactly.
  zine: {
    id: "zine",
    label: "Zine",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "zine",
    globeScale: 0.42,
    ocean: "#f4efe4",
    land: "#cfe0ec",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "#3255a4",
    coast: "#ff48b0",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#3255a4",
    lake: "#f4efe4",
    ice: "#f4efe4",
    relief: "#3255a4",
    dot: "#ff48b0",
    dotStroke: "#f4efe4",
    fresh: "#ffe800",
    tuned: "#3255a4",
    arc: "#3255a4",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Primary: after the feel of the De Stijl movement of the 1910s and 20s, and no copy of any painting
  // (src/map/stijl.ts). Land as flat rectangles of a grid fixed to longitude and latitude, divided by thick black
  // lines, mostly white and light grey with a fixed seeded few in yellow or blue (never red); a plain pale sea.
  // Round black markers with a white edge, so none reads as a cell; red for fresh reports.
  stijl: {
    id: "stijl",
    label: "Primary",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "stijl",
    globeScale: 0.44,
    ocean: "#e7e5dd",
    land: "#fdfcf8",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#111111",
    coastWidth: 3,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#e7e5dd",
    ice: "#fdfcf8",
    relief: "rgba(0,0,0,0)",
    dot: "#111111",
    dotStroke: "#ffffff",
    fresh: "#d62a1e",
    tuned: "#111111",
    arc: "#1d4fa0",
    glow: false,
    pinRing: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Herbarium (experimental): after the feel of a botanist's herbarium, pressed plants on heavy cream mounting paper
  // (src/map/herbarium.ts). Land as pressed foliage in faded greens and browns, coloured by latitude and relief, a fine
  // ink coast, the sea as the sheet with pencil water lines and pressed specimens at tested open-sea spots; the globe a
  // pressed-paper ball on a round card mount. Ink specimen-pin markers with a short shadow, rust for fresh reports.
  herbarium: {
    id: "herbarium",
    label: "Herbarium",
    experimental: true,
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "herbarium",
    globeScale: 0.38,
    ocean: "#f3ecdc",
    land: "#bdb690",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0)",
    coast: "#2f2a24",
    coastWidth: 0.85,
    waterlines: 0,
    waterline: "rgba(84,84,90,0.34)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(78,92,112,0.4)",
    lake: "#f3ecdc",
    ice: "#e8e1ce",
    relief: "rgba(0,0,0,0)",
    dot: "#2b2520",
    dotStroke: "#f7f1e2",
    fresh: "#b24a28",
    tuned: "#2b2520",
    arc: "#6f5a88",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Woodblock: after the feel of Japanese colour woodblock prints of the 1800s, our own drawings in
  // that manner and none copied (src/map/woodblock.ts). Flat Prussian blue sea stepped paler toward the shore, soft
  // green and ochre land in a black keyblock coast, curling wave crests at tested open-sea spots, bands of cloud
  // behind the globe. Small vermilion dots with a black keyline, washi white for fresh reports.
  woodblock: {
    id: "woodblock",
    label: "Woodblock",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "woodblock",
    globeScale: 0.4,
    ocean: "#1f4f7d",
    land: "#97a873",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#1d1b18",
    coastWidth: 1.15,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#3c6f9c",
    lake: "#3c6f9c",
    ice: "#efece2",
    relief: "#6d8656",
    dot: "#c4472d",
    dotStroke: "#1d1b18",
    fresh: "#faf3e2",
    tuned: "#1d1b18",
    arc: "#faf3e2",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Tiramisu (experimental): the world as a tiramisu (src/map/tiramisu.ts). The land is the mascarpone cream, spoon
  // swirled and dusted with cocoa toward its edges and on high relief; the sea is the coffee-soaked sponge under it.
  // The map is the top of a glass dish whose side shows the layers; the globe sits in a round glass bowl on a plate.
  // Coffee bean markers in dark roast, a light-roast caramel bean for fresh reports.
  tiramisu: {
    id: "tiramisu",
    label: "Tiramisu",
    experimental: true,
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "tiramisu",
    globeScale: 0.34,
    ocean: "#3a2416",
    land: "#f4e9d0",
    landTexture: "none",
    pixel: 1,
    dotShape: "bean",
    textureInk: "rgba(0,0,0,0)",
    coast: "#5a3a24",
    coastWidth: 0.9,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(122,78,46,0.5)",
    lake: "#3a2416",
    ice: "#fbf5e8",
    relief: "rgba(0,0,0,0)",
    dot: "#3b2112",
    dotStroke: "#fbf3e2",
    fresh: "#c4691d",
    tuned: "#3b2112",
    arc: "#9a5a2c",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
};

/**
 * The Design menu in labelled groups (decision 77). Ids missing from THEMES are skipped, so designs being added
 * elsewhere slot in by id, and any design not listed here lands in "Other", so none ever drops out of the menu.
 */
export const DESIGN_GROUPS: readonly { label: string; ids: readonly string[] }[] = [
  { label: "Paper, ink and craft", ids: ["morning", "cabinet", "blueprint", "pirate", "arcadia", "stitch", "glass", "sketch", "chalk", "popup", "zine", "woodblock", "stijl"] },
  { label: "Screens and signals", ids: ["wire", "ops", "newsroom", "terminal", "sheet", "radar", "noir", "stadium", "drive", "rave", "render", "desktop"] },
  { label: "Games and toys", ids: ["bit8", "bit16", "bit64", "arcade", "trainset", "candy", "crunch", "snow", "cube", "dual", "realm", "tactical", "blocks", "reef", "pindrop"] },
  { label: "Nature and sky", ids: ["pond", "honeycomb", "aquarium", "space"] },
  { label: "Places and moods", ids: ["nightcap", "campus", "lasso", "prep", "rail", "club", "pool", "lava", "realize", "arcana", "deli", "marquee", "postcard"] },
];

/**
 * The designs listed first in the Design menu (decision 111): a short set that shows the range, so a reader isn't met
 * with fifty names. Every other design stays in its group below.
 */
export const FEATURED: readonly string[] = ["morning", "cabinet", "blueprint", "arcadia", "stitch", "glass", "wire", "drive", "nightcap", "cube"];

/** The Design menu's groups for the designs that exist, each design exactly once, in the order listed. */
export function designMenu(ids: readonly string[]): { label: string; ids: ThemeId[] }[] {
  const have = new Set(ids);
  const placed = new Set<string>();
  const groups: { label: string; ids: ThemeId[] }[] = [];
  const featured = FEATURED.filter((id) => have.has(id)) as ThemeId[];
  featured.forEach((id) => placed.add(id));
  groups.push({ label: "Featured", ids: featured });
  for (const g of DESIGN_GROUPS) {
    const list: ThemeId[] = [];
    for (const id of g.ids) {
      if (!have.has(id) || placed.has(id)) continue;
      placed.add(id);
      list.push(id as ThemeId);
    }
    groups.push({ label: g.label, ids: list });
  }
  const rest = ids.filter((id) => !placed.has(id)) as ThemeId[];
  groups.push({ label: "Other", ids: rest.filter((id) => !THEMES[id]?.experimental) });
  groups.push({ label: "Experiments", ids: rest.filter((id) => THEMES[id]?.experimental) });
  return groups.filter((g) => g.ids.length > 0);
}
