import type { MarkShape } from "./map/marks.ts";
import type { SceneryKind } from "./map/scenery.ts";
import type { RGB } from "./map/terrain.ts";
import { geoEqualEarth, geoEquirectangular, geoNaturalEarth1, type GeoProjection } from "d3-geo";

export type ThemeId = "morning" | "cabinet" | "wire" | "ops" | "blueprint" | "pirate" | "space" | "candy" | "bit8" | "bit16" | "bit64" | "realize" | "newsroom" | "pond" | "honeycomb" | "arcana" | "arcadia" | "nightcap" | "campus" | "lasso" | "drive" | "stitch" | "glass" | "sheet" | "terminal" | "prep" | "rail";
export type ViewMode = "2d" | "3d";

/**
 * Everything the canvas needs to draw one look. UI chrome (fonts, panel colours)
 * lives in style.css under [data-theme=...]; keep the two in step.
 */
export interface Theme {
  id: ThemeId;
  label: string;
  defaultView: ViewMode;
  projection2d: () => GeoProjection;
  ocean: string;
  land: string;
  /**
   * Land texture: halftone dots, a dot matrix, a checkerboard dither, diagonal hatching, bevelled blocks like a
   * tiled game stage, pixel grass, loose paint strokes, or plain fill. Blocks, grass and paint use `textureInk2`
   * as their second colour.
   */
  landTexture: "halftone" | "matrix" | "dither" | "hatch" | "blocks" | "grass" | "brush" | "mottle" | "honeycomb" | "none";
  /**
   * Screen pixels per canvas pixel. 1 draws at full resolution; 3 draws a third as many pixels and scales them up
   * unsmoothed, so lines, coasts and dots come out as chunky pixels (Stage Select and Overworld).
   */
  pixel: number;
  /** With `pixel` above 1: enlarge the canvas smoothed, so it looks soft like an early 3D console's picture. */
  smooth?: boolean;
  /** Globe only: draw the sphere's outline as a polygon of this many sides, like a low-poly model. */
  polyGlobe?: number;
  /** Distance haze: toward the globe's rim, or toward the far edge of a tilted map. The colour of the horizon. */
  fog?: string;
  /** Place dots as circles, squares (the pixel designs), diamonds, bevelled discs or hexagons. */
  dotShape: MarkShape;
  textureInk: string;
  textureInk2?: string;
  coast: string;
  coastWidth: number;
  /** Concentric strokes around coasts, the old engraved-map trick. */
  waterlines: number;
  waterline: string;
  oceanHatch: string | null;
  /**
   * A pattern over the sea in canvas pixels: "tiles" is a faint square grid like a stage built from tiles,
   * "shimmer" is short broken highlights like light on water. Its ink is `waterline`.
   */
  oceanPattern?: "tiles" | "shimmer" | "brush" | "mottle";
  /** A wide band of lighter water along every coast, like the shallows on a game's world map. */
  shallows?: string;
  /**
   * Land built like early 3D game terrain (src/map/terrain.ts, decision 63): a grid of triangles with heights and
   * baked light, coloured grass, rock and snow, standing on cliff walls textured in `cliff` (base, light, dark),
   * with a band of `shallows` along the coast. Lakes and rivers are left out, since they no longer line up with
   * the grid.
   */
  lowPoly?: { grass: RGB; rock: RGB; snow: RGB; snowShade: RGB; cliff: [string, string, string]; shallows: string };
  /** Map view only: tilt the flat map back this many degrees, seen in perspective like the ground in a 3D game. */
  tilt?: number;
  /** A sky drawn behind the map: zenith, middle and horizon colours, with clouds that pan with the camera. */
  sky?: [string, string, string];
  /** With `tilt`: the eye's distance from the picture in frame heights (default 1). Smaller is stronger perspective. */
  tiltEye?: number;
  /** With `tilt`: the draw distance, as the smallest perspective scale drawn (default 0.5). */
  tiltFar?: number;
  /** With `tilt`: the furthest out Map view may zoom (default 1.8). */
  tiltMinZoom?: number;
  /** The globe's radius at the widest zoom, as a share of the frame's shorter side (default 0.46). */
  globeScale?: number;
  /**
   * Land and sea drawn a way of their own instead of the fills and textures above (decision 70): "neon" is Night
   * Drive's glowing wireframe over a ruled sea (src/map/neon.ts), "stitch" is Cross Stitch's X stitches on linen
   * (src/map/stitch.ts), "glass" is Rose Window's leaded glass (src/map/glass.ts). The colours above still set the
   * sea, land, coast, grid and markers.
   * Decision 74 adds "sheet" (Spreadsheet's filled cells, src/map/sheet.ts), "terminal" (Market Terminal's
   * dot-matrix plot, src/map/terminal.ts), "club" (Country Club's embroidery and desk globe, src/map/club.ts) and
   * "rail" (Sleeper Car's view from a train window, src/map/rail.ts).
   */
  surface?: "neon" | "stitch" | "glass" | "sheet" | "terminal" | "club" | "rail";
  graticule: string;
  graticuleDash: number[];
  river: string;
  lake: string;
  ice: string;
  relief: string;
  dot: string;
  dotStroke: string;
  /** Colour for places with a report in the last hour. */
  fresh: string;
  tuned: string;
  arc: string;
  glow: boolean;
  /** Globe only: a soft halo around the sphere. */
  atmosphere: string | null;
  /** Globe only: darkening toward the limb, so the sphere reads as lit from the upper left. */
  shade: string | null;
  /** Map only: a double rule around the sheet, like a printed chart. */
  neatline: boolean;
  /**
   * Decoration drawn under the dots (src/map/decor.ts): "sea" fills open ocean with engraved sea monsters, ships,
   * whirlpools, compass roses and wave marks,
   * "space" adds a thin bright rim to the globe and faint stars in the flat map's ocean, "candy" puts small
   * outlined sweets in open ocean. Never text, never on land, never near a
   * place.
   */
  decor: "sea" | "space" | "candy" | null;
  /**
   * Pictures that say what a design is (src/map/scenery.ts, decision 69): lily pads and frogs, a moon with a
   * sleeping bear, The Course of Empire's landmarks, or trick-rope loops with a denim sea. Open ocean or outside
   * the map only, never text.
   */
  scenery?: SceneryKind;
}

export const THEMES: Record<ThemeId, Theme> = {
  morning: {
    id: "morning",
    label: "Morning Edition",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#f3efe4",
    land: "#e6e0d0",
    landTexture: "halftone",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(21,21,21,0.55)",
    coast: "#151515",
    coastWidth: 0.9,
    waterlines: 4,
    waterline: "rgba(21,21,21,0.16)",
    oceanHatch: null,
    graticule: "rgba(21,21,21,0.18)",
    graticuleDash: [2, 3],
    river: "rgba(21,21,21,0.45)",
    lake: "#f3efe4",
    ice: "#f7f4ec",
    relief: "rgba(21,21,21,0.55)",
    dot: "#151515",
    dotStroke: "#f3efe4",
    fresh: "#151515",
    tuned: "#151515",
    arc: "rgba(21,21,21,0.7)",
    glow: false,
    atmosphere: null,
    shade: "rgba(21,21,21,0.22)",
    neatline: true,
    decor: null,
  },
  cabinet: {
    id: "cabinet",
    label: "Cabinet Map",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#e4d3ab",
    land: "#efe2c2",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(58,42,24,0.4)",
    coast: "#3a2a18",
    coastWidth: 1,
    waterlines: 5,
    waterline: "rgba(58,42,24,0.13)",
    oceanHatch: "rgba(58,42,24,0.07)",
    graticule: "rgba(58,42,24,0.28)",
    graticuleDash: [],
    river: "rgba(40,70,95,0.55)",
    lake: "#dccaa0",
    ice: "#f4ecd8",
    relief: "rgba(58,42,24,0.6)",
    dot: "#3a2a18",
    dotStroke: "#efe2c2",
    fresh: "#8e2a1c",
    tuned: "#8e2a1c",
    arc: "rgba(142,42,28,0.75)",
    glow: false,
    atmosphere: null,
    shade: "rgba(58,42,24,0.3)",
    neatline: true,
    decor: null,
  },
  wire: {
    id: "wire",
    label: "Wire Room",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#020503",
    land: "#04100a",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(76,255,140,0.34)",
    coast: "rgba(96,255,150,0.62)",
    coastWidth: 0.7,
    waterlines: 0,
    waterline: "rgba(96,255,150,0.06)",
    oceanHatch: null,
    graticule: "rgba(96,255,150,0.09)",
    graticuleDash: [],
    river: "rgba(96,255,150,0.18)",
    lake: "#020503",
    ice: "#07170e",
    relief: "rgba(96,255,150,0.22)",
    dot: "#6dff9e",
    dotStroke: "#020503",
    fresh: "#e6fff0",
    tuned: "#e6fff0",
    arc: "rgba(109,255,158,0.8)",
    glow: true,
    atmosphere: "rgba(76,255,140,0.16)",
    shade: "rgba(0,0,0,0.55)",
    neatline: false,
    decor: null,
  },
  ops: {
    id: "ops",
    label: "Ops Room",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#0e1217",
    land: "#1a2028",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(170,186,204,0.3)",
    coast: "rgba(170,186,204,0.55)",
    coastWidth: 0.8,
    waterlines: 0,
    waterline: "rgba(170,186,204,0.06)",
    oceanHatch: null,
    graticule: "rgba(170,186,204,0.12)",
    graticuleDash: [1, 3],
    river: "rgba(120,170,200,0.22)",
    lake: "#0e1217",
    ice: "#232b35",
    relief: "rgba(170,186,204,0.2)",
    dot: "#c8d2dd",
    dotStroke: "#0e1217",
    fresh: "#43c1d3",
    tuned: "#43c1d3",
    arc: "rgba(67,193,211,0.85)",
    glow: false,
    atmosphere: "rgba(67,193,211,0.10)",
    shade: "rgba(0,0,0,0.45)",
    neatline: true,
    decor: null,
  },
  blueprint: {
    id: "blueprint",
    label: "Blueprint",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#17397a",
    land: "#1d4590",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(238,243,251,0.3)",
    coast: "#eef3fb",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(238,243,251,0.22)",
    oceanHatch: null,
    graticule: "rgba(238,243,251,0.16)",
    graticuleDash: [],
    river: "rgba(238,243,251,0.35)",
    lake: "#17397a",
    ice: "#2451a0",
    relief: "rgba(238,243,251,0.45)",
    dot: "#eef3fb",
    dotStroke: "#17397a",
    fresh: "#ff8a52",
    tuned: "#ff8a52",
    arc: "rgba(255,138,82,0.9)",
    glow: false,
    atmosphere: "rgba(238,243,251,0.12)",
    shade: "rgba(8,20,48,0.5)",
    neatline: true,
    decor: null,
  },
  pirate: {
    id: "pirate",
    label: "Pirate",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#b3cbc0",
    land: "#eddab0",
    landTexture: "none",
    pixel: 1,
    dotShape: "star4",
    textureInk: "rgba(59,38,20,0.4)",
    coast: "#3b2614",
    coastWidth: 1.1,
    waterlines: 3,
    waterline: "rgba(59,38,20,0.2)",
    oceanHatch: null,
    graticule: "rgba(59,38,20,0.3)",
    graticuleDash: [5, 4],
    river: "rgba(40,78,88,0.5)",
    lake: "#b3cbc0",
    ice: "#f4e9cf",
    relief: "rgba(59,38,20,0.6)",
    dot: "#3b2614",
    dotStroke: "#eddab0",
    fresh: "#b0271d",
    tuned: "#b0271d",
    arc: "rgba(176,39,29,0.8)",
    glow: false,
    atmosphere: null,
    shade: "rgba(59,38,20,0.32)",
    neatline: true,
    decor: "sea",
  },
  space: {
    id: "space",
    label: "Space",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#070b20",
    land: "#1a2552",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(255,212,150,0.34)",
    coast: "rgba(160,200,255,0.75)",
    coastWidth: 0.7,
    waterlines: 0,
    waterline: "rgba(150,192,255,0.06)",
    oceanHatch: null,
    graticule: "rgba(150,192,255,0.24)",
    graticuleDash: [2, 5],
    river: "rgba(150,192,255,0.16)",
    lake: "#070b20",
    ice: "#222c5e",
    relief: "rgba(150,192,255,0.2)",
    dot: "#eef3ff",
    dotStroke: "#070b20",
    fresh: "#ffb454",
    tuned: "#ffb454",
    arc: "rgba(255,180,84,0.85)",
    glow: true,
    atmosphere: "rgba(110,170,255,0.24)",
    shade: "rgba(0,0,10,0.6)",
    neatline: true,
    decor: "space",
  },
  candy: {
    id: "candy",
    label: "Candy Shop",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#cbe8ff",
    land: "#ffd8ec",
    landTexture: "none",
    pixel: 1,
    dotShape: "gumdrop",
    textureInk: "rgba(226,127,180,0.3)",
    coast: "#e27fb4",
    coastWidth: 1.2,
    waterlines: 2,
    waterline: "rgba(255,255,255,0.85)",
    oceanHatch: null,
    graticule: "rgba(255,255,255,0.75)",
    graticuleDash: [2, 5],
    river: "rgba(110,170,225,0.7)",
    lake: "#cbe8ff",
    ice: "#ffffff",
    relief: "rgba(226,127,180,0.55)",
    dot: "#5b3f8c",
    dotStroke: "#ffffff",
    fresh: "#d9307a",
    tuned: "#d9307a",
    arc: "rgba(217,48,122,0.85)",
    glow: false,
    atmosphere: "rgba(255,170,215,0.5)",
    shade: "rgba(110,80,160,0.2)",
    neatline: false,
    decor: "candy",
  },
  // Nods to three generations of home consoles, each after the sense of place of one game series of its era, never
  // its art, names, logos or characters. Stage Select after Mega Man: hard 8-bit pixels, a wall of bevelled metal
  // blocks, riveted stage-select frames. Overworld after Final Fantasy's world maps: finer pixels, grass, sandy
  // shores and shallows, blue windows. Polygon Kingdom after Super Mario 64 and Ocarina of Time: a tilted camera
  // over triangle terrain with baked light, orange cliffs, a pale sky and fog at the draw distance, a soft picture,
  // bevelled gold markers floating over their shadows, and a menu title in ice blue (decision 63).
  bit8: {
    id: "bit8",
    label: "Stage Select",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#0000a8",
    land: "#008888",
    landTexture: "blocks",
    pixel: 3,
    dotShape: "square",
    textureInk: "#003c48",
    textureInk2: "#40e0d0",
    coast: "#000000",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(0,88,248,0.45)",
    oceanHatch: null,
    oceanPattern: "tiles",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#3cbcfc",
    lake: "#0000a8",
    ice: "#fcfcfc",
    relief: "#003c48",
    dot: "#fcfcfc",
    dotStroke: "#000000",
    fresh: "#f83800",
    tuned: "#f8b800",
    arc: "#f8b800",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  bit16: {
    id: "bit16",
    label: "Overworld",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2048a8",
    land: "#58a830",
    landTexture: "grass",
    pixel: 2,
    dotShape: "circle",
    textureInk: "#2f6c1c",
    textureInk2: "#98d860",
    coast: "#f0e0a0",
    coastWidth: 1.6,
    waterlines: 0,
    waterline: "rgba(210,236,255,0.6)",
    oceanHatch: null,
    oceanPattern: "shimmer",
    shallows: "#3c78d8",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "#78b8f8",
    lake: "#3c78d8",
    ice: "#f8f8f8",
    relief: "#7a4a1c",
    dot: "#f8f8f8",
    dotStroke: "#101830",
    fresh: "#f8d030",
    tuned: "#f8d030",
    arc: "#f8d030",
    glow: false,
    atmosphere: "rgba(150,200,255,0.45)",
    shade: "rgba(0,0,40,0.45)",
    neatline: false,
    decor: null,
  },
  bit64: {
    id: "bit64",
    label: "Polygon Kingdom",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    ocean: "#3d8fdc",
    land: "#5cc83a",
    landTexture: "none",
    lowPoly: {
      grass: [92, 200, 58],
      rock: [165, 138, 106],
      snow: [244, 246, 255],
      snowShade: [185, 196, 224],
      cliff: ["#c0621e", "#e08a3a", "#8a3a0c"],
      shallows: "#62c6e6",
    },
    tilt: 58,
    sky: ["#6fb4f0", "#a9d6f7", "#e6f5fb"],
    fog: "#e6f5fb",
    pixel: 1.5,
    smooth: true,
    polyGlobe: 22,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0)",
    coast: "rgba(0,0,0,0)",
    coastWidth: 0,
    waterlines: 0,
    waterline: "rgba(159,216,248,0.4)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#3d8fdc",
    ice: "#f4f6ff",
    relief: "#6e4418",
    dot: "#ffd23a",
    dotStroke: "#8a5600",
    fresh: "#ff4a3d",
    tuned: "#ffffff",
    arc: "#ffffff",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },




  // Direct nods to the Mezmerize and Hypnotize covers (2005): black ground, dark red smeared paint, bone white, the
  // striped arcs, the blue face for fresh reports, a white stamped poster face over red marker lettering. No band
  // name or artwork is copied.
  realize: {
    id: "realize",
    label: "Realize",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#0b090a",
    land: "#4a1512",
    landTexture: "brush",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(150,32,28,0.5)",
    textureInk2: "rgba(0,0,0,0.5)",
    coast: "#d8ccb2",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "rgba(120,18,24,0.13)",
    oceanHatch: null,
    oceanPattern: "brush",
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(216,204,178,0.22)",
    lake: "#0b090a",
    ice: "#6e645a",
    relief: "rgba(0,0,0,0.6)",
    dot: "#ece3d0",
    dotStroke: "#0b090a",
    fresh: "#7d9be0",
    tuned: "#d2263b",
    arc: "#d2263b",
    glow: false,
    atmosphere: "rgba(150,20,30,0.35)",
    shade: "rgba(0,0,0,0.7)",
    neatline: false,
    decor: null,
  },

  // A modern television news studio: the world on a glowing LED wall, glossy navy glass, white and red captions
  // along the bottom of the screen, and a crawl of headlines.
  newsroom: {
    id: "newsroom",
    label: "Newsroom",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#07163a",
    land: "#12357a",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(140,200,255,0.55)",
    coast: "#6cc4ff",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(108,196,255,0.2)",
    oceanHatch: null,
    graticule: "rgba(108,196,255,0.14)",
    graticuleDash: [],
    river: "rgba(108,196,255,0.3)",
    lake: "#07163a",
    ice: "#2a4f94",
    relief: "rgba(140,200,255,0.3)",
    dot: "#ffffff",
    dotStroke: "#051030",
    fresh: "#ff3b4e",
    tuned: "#ffffff",
    arc: "#ff3b4e",
    glow: true,
    atmosphere: "rgba(80,170,255,0.45)",
    shade: "rgba(0,4,20,0.6)",
    neatline: false,
    decor: null,
  },
  // A frog pond seen from above: murky green water, lily pads with lotus flowers, frogs and dragonflies in open
  // water, lotus pink for fresh reports (decision 69).
  pond: {
    id: "pond",
    label: "Frog Pond",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2f6b5f",
    land: "#76b347",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "pad",
    textureInk: "rgba(170,220,110,0.7)",
    textureInk2: "rgba(40,110,40,0.55)",
    coast: "#24501d",
    coastWidth: 1.4,
    waterlines: 3,
    waterline: "rgba(190,235,215,0.35)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(190,235,215,0.5)",
    lake: "#2f6b5f",
    ice: "#e8f2e4",
    relief: "rgba(30,80,30,0.5)",
    dot: "#fff6d8",
    dotStroke: "#1e3b17",
    fresh: "#ff7eb6",
    tuned: "#ff7eb6",
    arc: "#ff7eb6",
    glow: false,
    atmosphere: "rgba(120,200,160,0.35)",
    shade: "rgba(0,30,20,0.45)",
    neatline: false,
    decor: null,
    scenery: "pond",
  },
  // Inside a hive, after the feel of Bee Movie: honey land built from hexagon cells over a dark hive, black and
  // yellow stripes in the chrome, hexagon markers.
  honeycomb: {
    id: "honeycomb",
    label: "Honeycomb",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#2e1c07",
    land: "#f2b632",
    landTexture: "honeycomb",
    pixel: 1,
    dotShape: "hex",
    textureInk: "rgba(160,95,10,0.75)",
    textureInk2: "rgba(255,225,140,0.6)",
    coast: "#1a1004",
    coastWidth: 1.6,
    waterlines: 2,
    waterline: "rgba(242,182,50,0.18)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(160,95,10,0.6)",
    lake: "#2e1c07",
    ice: "#fbe7a8",
    relief: "rgba(120,70,5,0.6)",
    dot: "#1a1004",
    dotStroke: "#ffd84a",
    fresh: "#ffffff",
    tuned: "#ffffff",
    arc: "#ffffff",
    glow: false,
    atmosphere: "rgba(242,182,50,0.35)",
    shade: "rgba(0,0,0,0.55)",
    neatline: false,
    decor: null,
  },
  // A tarot card: midnight indigo, gold linework and stars, the sheet framed like a card.
  arcana: {
    id: "arcana",
    label: "Tarot",
    defaultView: "3d",
    projection2d: geoEqualEarth,
    ocean: "#161338",
    land: "#2b2560",
    landTexture: "matrix",
    pixel: 1,
    dotShape: "star5",
    textureInk: "rgba(232,196,110,0.4)",
    coast: "#e3bd62",
    coastWidth: 1.2,
    waterlines: 1,
    waterline: "rgba(227,189,98,0.25)",
    oceanHatch: null,
    graticule: "rgba(227,189,98,0.12)",
    graticuleDash: [1, 4],
    river: "rgba(227,189,98,0.3)",
    lake: "#161338",
    ice: "#3a3378",
    relief: "rgba(227,189,98,0.45)",
    dot: "#f5e6c0",
    dotStroke: "#161338",
    fresh: "#ff9d5c",
    tuned: "#f5e6c0",
    arc: "#e3bd62",
    glow: false,
    atmosphere: "rgba(227,189,98,0.28)",
    shade: "rgba(5,0,20,0.6)",
    neatline: true,
    decor: null,
  },
  // After Thomas Cole's The Course of Empire (public domain): a painted bay in evening light, olive land in loose
  // strokes, and the paintings' crag, lone column, temple and broken arch standing in the water (decision 69).
  arcadia: {
    id: "arcadia",
    label: "Arcadia",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#4d6b73",
    land: "#7f7a44",
    landTexture: "brush",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(200,178,96,0.5)",
    coast: "#2b2314",
    coastWidth: 1.2,
    waterlines: 2,
    waterline: "rgba(255,226,160,0.35)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(255,226,160,0.5)",
    lake: "#4d6b73",
    ice: "#eadfc4",
    relief: "rgba(34,27,14,0.85)",
    dot: "#f6ecd2",
    dotStroke: "#2a2014",
    fresh: "#d2452a",
    tuned: "#f6ecd2",
    arc: "#d2452a",
    glow: false,
    atmosphere: "rgba(255,206,130,0.5)",
    shade: "rgba(20,14,4,0.5)",
    neatline: false,
    decor: null,
    scenery: "empire",
    textureInk2: "rgba(40,44,18,0.45)",
  },
  // A bedtime tea box: a watercolour night in periwinkle and sage, stars over the sea, and a bear in a nightcap asleep
  // in the moon beside the globe (decision 69).
  nightcap: {
    id: "nightcap",
    label: "Bedtime Tea",
    defaultView: "3d",
    projection2d: geoNaturalEarth1,
    ocean: "#3b4a7e",
    land: "#a8c39a",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "flower",
    textureInk: "rgba(235,240,210,0.55)",
    textureInk2: "rgba(90,130,100,0.35)",
    coast: "#34466e",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(200,215,255,0.3)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(230,236,255,0.5)",
    lake: "#3b4a7e",
    ice: "#f4f2ea",
    relief: "rgba(52,70,110,0.45)",
    dot: "#fff8e6",
    dotStroke: "#34466e",
    fresh: "#ffb35c",
    tuned: "#fff8e6",
    arc: "#ffb35c",
    glow: false,
    atmosphere: "rgba(255,240,190,0.35)",
    shade: "rgba(30,30,80,0.45)",
    neatline: false,
    decor: null,
    scenery: "tea",
  },
  // A college campus in maroon and cream: maroon land on cream paper, varsity lettering, pennant buttons.
  campus: {
    id: "campus",
    label: "Campus",
    defaultView: "2d",
    projection2d: geoEqualEarth,
    ocean: "#f3ede1",
    land: "#881c1c",
    landTexture: "hatch",
    pixel: 1,
    dotShape: "shield",
    textureInk: "rgba(255,255,255,0.18)",
    coast: "#4e0d0d",
    coastWidth: 1,
    waterlines: 2,
    waterline: "rgba(136,28,28,0.25)",
    oceanHatch: null,
    graticule: "rgba(136,28,28,0.1)",
    graticuleDash: [],
    river: "rgba(243,237,225,0.4)",
    lake: "#f3ede1",
    ice: "#fbf8f1",
    relief: "rgba(255,255,255,0.35)",
    dot: "#ffffff",
    dotStroke: "#2a0808",
    fresh: "#f0b323",
    tuned: "#2a0808",
    arc: "#2a0808",
    glow: false,
    atmosphere: "rgba(136,28,28,0.25)",
    shade: "rgba(60,0,0,0.35)",
    neatline: false,
    decor: null,
  },
  // A trick roper's frontier: a denim sea with orange seams along every coast, tan leather land, a rope around the
  // sheet and spinning rope loops over the water (decision 69).
  lasso: {
    id: "lasso",
    label: "Lasso",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    ocean: "#46698c",
    land: "#c99a62",
    landTexture: "mottle",
    pixel: 1,
    dotShape: "star6",
    textureInk: "rgba(240,205,150,0.4)",
    coast: "#4a2e16",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(74,46,22,0.3)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(70,105,140,0.7)",
    lake: "#46698c",
    ice: "#f1e7d2",
    relief: "rgba(90,55,25,0.7)",
    dot: "#fbf3df",
    dotStroke: "#3a2410",
    fresh: "#b3322a",
    tuned: "#3a2410",
    arc: "#b3322a",
    glow: false,
    atmosphere: "rgba(211,177,132,0.4)",
    shade: "rgba(60,30,0,0.35)",
    neatline: false,
    decor: null,
    scenery: "rope",
    textureInk2: "rgba(110,62,22,0.3)",
  },
  // Decision 70: three designs that draw the world a way of their own.
  // Night Drive: a 1980s night drive. The flat map is seen low over a black sea ruled by a glowing magenta grid,
  // receding to a horizon under a striped setting sun; land is a cyan wireframe with wire mountains.
  drive: {
    id: "drive",
    label: "Night Drive",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "neon",
    globeScale: 0.32,
    tilt: 66,
    tiltEye: 0.5,
    tiltFar: 0.3,
    tiltMinZoom: 1.4,
    sky: ["#0d0221", "#4a1068", "#ff7a3d"],
    fog: "#ff4f9a",
    ocean: "#07010f",
    land: "#0d0628",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(111,246,255,0.45)",
    coast: "#6ff6ff",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "#ff4fd8",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#07010f",
    ice: "#0d0628",
    relief: "#9ffbff",
    dot: "#ffe14d",
    dotStroke: "#1a0530",
    fresh: "#ff4fd8",
    tuned: "#ffffff",
    arc: "#6ff6ff",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Cross Stitch: an embroidered sampler. Land in X stitches on linen aida cloth, threads by climate and relief,
  // coasts in backstitch, the globe held in a wooden embroidery hoop, markers as sewn buttons.
  stitch: {
    id: "stitch",
    label: "Cross Stitch",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "stitch",
    globeScale: 0.32,
    ocean: "#efe6d2",
    land: "#6f9a4a",
    landTexture: "none",
    pixel: 1,
    dotShape: "button",
    textureInk: "rgba(120,96,60,0.28)",
    coast: "#4a3326",
    coastWidth: 1.6,
    waterlines: 0,
    waterline: "#a9c6db",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#efe6d2",
    ice: "#fbfaf5",
    relief: "#8a6040",
    dot: "#9e1f4a",
    dotStroke: "#f6efdd",
    fresh: "#1f6fd1",
    tuned: "#4a3326",
    arc: "#b0304a",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Rose Window: stained glass. Land and sea cut into pieces of jewel-toned glass held in dark lead, lit from
  // behind; the globe is the centre of a round window in stone tracery.
  glass: {
    id: "glass",
    label: "Rose Window",
    defaultView: "3d",
    projection2d: geoEquirectangular,
    surface: "glass",
    globeScale: 0.27,
    ocean: "#1b3f8f",
    land: "#2f8a4a",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(0,0,0,0)",
    coast: "#16121c",
    coastWidth: 3.2,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#1b3f8f",
    ice: "#dfe8f2",
    relief: "#7a4a9a",
    dot: "#fff4d2",
    dotStroke: "#16121c",
    fresh: "#ffc21a",
    tuned: "#fff4d2",
    arc: "#fff4d2",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Decision 74: four designs that borrow the feel of familiar things and name none of them.
  // Spreadsheet: the world as filled cells in a grid, shaded like conditional formatting by relief; the globe is a
  // chart object on the sheet (src/map/sheet.ts).
  sheet: {
    id: "sheet",
    label: "Spreadsheet",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "sheet",
    globeScale: 0.34,
    ocean: "#ffffff",
    land: "#a3d18b",
    landTexture: "none",
    pixel: 1,
    dotShape: "square",
    textureInk: "rgba(0,0,0,0)",
    coast: "#3f6b50",
    coastWidth: 1.3,
    waterlines: 0,
    waterline: "#e1e3e6",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#ffffff",
    ice: "#e6edf5",
    relief: "#3f7d47",
    dot: "#24313d",
    dotStroke: "#ffffff",
    fresh: "#1f63d1",
    tuned: "#2d8653",
    arc: "#2d8653",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Market Terminal: amber on black, the land as a dot-matrix plot over a coordinate grid, the globe a vector plot
  // in a ring of ticks (src/map/terminal.ts). No prices, no arrows, no red or green.
  terminal: {
    id: "terminal",
    label: "Market Terminal",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "terminal",
    globeScale: 0.4,
    ocean: "#030303",
    land: "rgba(255,176,0,0.07)",
    landTexture: "none",
    pixel: 1,
    dotShape: "block",
    textureInk: "rgba(255,176,0,0.62)",
    coast: "#ffb000",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(0,0,0,0)",
    oceanHatch: null,
    graticule: "rgba(255,176,0,0.16)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#030303",
    ice: "rgba(255,230,190,0.1)",
    relief: "#ffd36b",
    dot: "#f4f4f4",
    dotStroke: "#030303",
    fresh: "#52c7ff",
    tuned: "#ffe066",
    arc: "#ffe066",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Country Club: preppy heritage clothing. The flat map is embroidered on oxford cloth, land in hunter green satin
  // stitch with a stitched edge; the globe is a leather desk globe tooled in gold on a brass stand (src/map/club.ts).
  prep: {
    id: "prep",
    label: "Country Club",
    defaultView: "2d",
    projection2d: geoNaturalEarth1,
    surface: "club",
    globeScale: 0.29,
    ocean: "#c9d7e8",
    land: "#2f5b3f",
    landTexture: "none",
    pixel: 1,
    dotShape: "bevel",
    textureInk: "rgba(255,255,255,0.13)",
    textureInk2: "rgba(0,0,0,0.16)",
    coast: "#1b3526",
    coastWidth: 1.2,
    waterlines: 0,
    waterline: "#f7f4ec",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#c9d7e8",
    ice: "#f1ead6",
    relief: "#8fb07a",
    dot: "#c9a043",
    dotStroke: "#1d2b4f",
    fresh: "#f6f1e4",
    tuned: "#1d2b4f",
    arc: "#b3262e",
    glow: false,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
  // Sleeper Car: the world from a long-distance train's window at dusk. Map view is the tilted camera over
  // farmland, sea and mountains to a horizon with hills, with telegraph poles and the next track passing in the
  // foreground; the globe hangs in the dusk sky (src/map/rail.ts). Markers are town lights.
  rail: {
    id: "rail",
    label: "Sleeper Car",
    defaultView: "2d",
    projection2d: geoEquirectangular,
    surface: "rail",
    globeScale: 0.3,
    tilt: 64,
    tiltEye: 0.56,
    tiltFar: 0.32,
    tiltMinZoom: 1.6,
    sky: ["#1b2550", "#6b5a8e", "#f2a86b"],
    fog: "#e6b48f",
    ocean: "#2a4a6e",
    land: "#8e9a5c",
    landTexture: "none",
    pixel: 1,
    dotShape: "circle",
    textureInk: "rgba(0,0,0,0)",
    coast: "#3b3424",
    coastWidth: 1,
    waterlines: 0,
    waterline: "rgba(255,236,200,0.5)",
    oceanHatch: null,
    graticule: "rgba(0,0,0,0)",
    graticuleDash: [],
    river: "rgba(0,0,0,0)",
    lake: "#2a4a6e",
    ice: "#eef0f2",
    relief: "#6a5d62",
    dot: "#ffd98a",
    dotStroke: "#3a2a14",
    fresh: "#8fe6ff",
    tuned: "#fff4d6",
    arc: "#ffe2a3",
    glow: true,
    atmosphere: null,
    shade: null,
    neatline: false,
    decor: null,
  },
};
